### ISSUE TITLE
Unable to Add Drop Shadow as Filter ignored

### ISSUE THREAD

**Issue by asj-it** [luberda-molinet/FFImageLoading#1288] opened 2019-06-01 13:13 UTC
### Description

I am using FFImageLoading to populate an imagebutton on a Xamarin forms project.

``` csharp
            var svgImageSource = SvgImageSource.FromResource("Listi.asjit.com.Svg.chat.svg", vectorHeight:1000, vectorWidth: 1000);
            Btn.Source = svgImageSource;
```
This loads the image fine.  But, I am trying to use the imagebutton as a floating button so would like a drop shadow.  Unfortunately, the drop shadow filter is being ignored

The SVG is : 
``` xml
<svg xmlns="http://www.w3.org/2000/svg"  version="1.1"  width="240" height="240" >
  <defs>
    <filter id="f3" x="0" y="0" width="200%" height="200%">
      <feOffset result="offOut" in="SourceAlpha" dx="20" dy="20" />
      <feGaussianBlur result="blurOut" in="offOut" stdDeviation="10" />
      <feBlend in="SourceGraphic" in2="blurOut" mode="normal" />
    </filter>
  </defs>
	<g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal" >
		<path d="M0,192v-192h192v192z" fill="none"/>
		<path d="M96,192c-53.01934,0 -96,-42.98066 -96,-96v0c0,-53.01934 42.98066,-96 96,-96v0c53.01934,0 96,42.98066 96,96v0c0,53.01934 -42.98066,96 -96,96z" fill="#00798c" filter="url(#f3)"  />
		<g id="original-icon" fill="#dbc2cf">
			<path d="M134.4,56h-76.8c-5.28,0 -9.552,4.32 -9.552,9.6l-0.048,86.4l19.2,-19.2h67.2c5.28,0 9.6,-4.32 9.6,-9.6v-57.6c0,-5.28 -4.32,-9.6 -9.6,-9.6zM91.2,75.2h9.6v9.6h-9.6zM91.2,94.4h9.6v19.2h-9.6z"/>
		</g>
	</g>
</svg>
```

### Steps to Reproduce

Load SVG into image button; 

### Expected Behavior

Image should be displayed with a drop shadow

### Actual Behavior

The image is displayed without the drop shadow.

### Basic Information

- Version with issue: 2.4.11.982
- Platform: Xamarin/IOS

### Screenshots

<img width="118" alt="Screenshot 2019-06-01 at 14 09 03" src="https://user-images.githubusercontent.com/16338022/58748909-0ae0f380-8477-11e9-9c9a-0ce2441158a7.png">

**Comment by daniel-luberda** [comment] 2019-06-06 18:13
Not yet implemented, duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/1205

**Closed by daniel-luberda** 2019-06-06 18:13 UTC
