### ISSUE TITLE
SVG rendering issue

### ISSUE THREAD

**Issue by franzdevel** [luberda-molinet/FFImageLoading#1186] opened 2019-01-16 05:36 UTC
### Description

I am using FFImageLoading for Xamarin / iOS app development. After upgrading my NuGet FFImageLoading package to version 2.4.4.859 my SVG images are not rendered correctly anymore.

This may be a duplicate of #1181 (I am not sure).

As an example, consider the following SVG image:

```
<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 60 60">
	<circle cx="30" cy="30" r="30" fill="#f0f0f0" />
	<g transform="translate(6,6)">
		<path d="M23.99 4C12.94 4 4 12.95 4 24s8.94 20 19.99 20C35.04 44 44 35.05 44 24S35.04 4 23.99 4zm13.85 12h-5.9c-.65-2.5-1.56-4.9-2.76-7.12 3.68 1.26 6.74 3.81 8.66 7.12zM24 8.07c1.67 2.4 2.97 5.07 3.82 7.93h-7.64c.85-2.86 2.15-5.53 3.82-7.93zM8.52 28C8.19 26.72 8 25.38 8 24s.19-2.72.52-4h6.75c-.16 1.31-.27 2.64-.27 4 0 1.36.11 2.69.28 4H8.52zm1.63 4h5.9c.65 2.5 1.56 4.9 2.76 7.13-3.68-1.26-6.74-3.82-8.66-7.13zm5.9-16h-5.9c1.92-3.31 4.98-5.87 8.66-7.13-1.2 2.23-2.11 4.63-2.76 7.13zM24 39.93c-1.66-2.4-2.96-5.07-3.82-7.93h7.64c-.86 2.86-2.16 5.53-3.82 7.93zM28.68 28h-9.36c-.19-1.31-.32-2.64-.32-4 0-1.36.13-2.69.32-4h9.36c.19 1.31.32 2.64.32 4 0 1.36-.13 2.69-.32 4zm.51 11.12c1.2-2.23 2.11-4.62 2.76-7.12h5.9c-1.93 3.31-4.99 5.86-8.66 7.12zM32.72 28c.16-1.31.28-2.64.28-4 0-1.36-.11-2.69-.28-4h6.75c.33 1.28.53 2.62.53 4s-.19 2.72-.53 4h-6.75z" fill="#000000" fill-opacity="0.45" />
	</g>
</svg>
```

This renders correctly with FFImageLoading 2.4.3.840. However, when using version 2.4.4.859 the translation command is ignored, leading to an incorrect rendering result (see attached screenshots below).

### Basic Information

**Version with issue:**

- Xamarin.FFImageLoading 2.4.4.859
- Xamarin.FFImageLoading.Forms 2.4.4.859
- Xamarin.FFImageLoading.Svg 2.4.4.859
- Xamarin.FFImageLoading.Svg.Forms 2.4.4.859

**Last known good version:**

- Xamarin.FFImageLoading 2.4.3.840
- Xamarin.FFImageLoading.Forms 2.4.3.840
- Xamarin.FFImageLoading.Svg 2.4.3.840
- Xamarin.FFImageLoading.Svg.Forms 2.4.3.840

**Platform:**

=== Visual Studio Community 2017 for Mac ===

Version 7.7.2 (build 21)
Installation UUID: 09e9f086-34f7-45e4-9db7-be3548ecb6dd
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/franzbrosch/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Users/franzbrosch/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Build Information ===

Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

### Screenshots

**Correct rendering with version 2.4.3.840:**

<img width="103" alt="v2-4-3-840-correct" src="https://user-images.githubusercontent.com/24537277/51228483-e0513b00-19ac-11e9-9825-d97fce90b9b5.png">

**Incorrect rendering with version 2.4.4.859:**

<img width="104" alt="v2-4-4-859-incorrect" src="https://user-images.githubusercontent.com/24537277/51228458-bc8df500-19ac-11e9-9096-9842ed9a4f5e.png">

**Comment by irongut** [comment] 2019-01-24 19:23
v2.4.4.859 has a bug with translations in SVGs. This is a duplicate of #1157 and the v2.4.5.860-pre prerelease may work for you although it has other issues. See [my coment](https://github.com/luberda-molinet/FFImageLoading/issues/1157#issuecomment-447601446) in that issue.

**Comment by ArvindSJoshi** [comment] 2019-01-28 17:08
I was facing the same issue and the 2.4.5.860-pre is working for me. However, the question is when is the 2.4.5.860 version scheduled to be released?

**Comment by daniel-luberda** [comment] 2019-04-06 14:43
Fixed

**Closed by daniel-luberda** 2019-04-06 14:43 UTC
