### ISSUE TITLE
[Android] CachedImage doesn't load in SFListView until after scrolled off screen

### ISSUE THREAD

**Issue by ChaseFlorell** [luberda-molinet/FFImageLoading#812] opened 2017-11-11 17:25 UTC
I'm finding some strange behavior whereby when I load a CachedImage into an ItemTemplate within an SFListView, I see a blank space where the image should be until I scroll.

Here's a template

```xml
<ContentView xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xaml="clr-namespace:MyApp.SelfServe.Mobile.Xaml;assembly=MyApp.SelfServe.Mobile"
             xmlns:forms="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:controls="clr-namespace:MyApp.SelfServe.Mobile.Controls;assembly=MyApp.SelfServe.Mobile"
             x:Class="MyApp.SelfServe.Mobile.Pages.UserAccount.Projects.Templates.ProjectListTemplate">
    <Grid HorizontalOptions="Fill" VerticalOptions="Fill" Margin="0" Padding="0"
          BackgroundColor="{Binding IsSelected, Converter={StaticResource SfListViewSelectionConverter}}"
          RowSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition>
                <RowDefinition.Height>
                    <OnPlatform x:TypeArguments="GridLength">
                        <On Platform="Android" Value="120" />
                        <On Platform="iOS" Value="100" />
                    </OnPlatform>
                </RowDefinition.Height>
            </RowDefinition>
            <RowDefinition Height="1" />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="5" />
            <ColumnDefinition Width="50" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="40" />
        </Grid.ColumnDefinitions>

        <BoxView Grid.Column="0"
                 Grid.Row="0"
                 Color="{Binding Phase, Converter={StaticResource ProjectPhaseToColorConverter}, ConverterParameter={Binding HasAlert}}"
                 WidthRequest="5"
                 HeightRequest="999"
                 VerticalOptions="FillAndExpand" />

        <forms:CachedImage Grid.Column="1" 
                           Grid.Row="0"
                           HorizontalOptions="Center"
                           VerticalOptions="Center"
                           Source="{Binding PhaseIcon}" />

        <StackLayout Grid.Column="2"
                     Grid.Row="0"
                     Spacing="2"
                     VerticalOptions="Center">
            <Label Text="{Binding Nickname}" Style="{StaticResource Common-Title}"
                   LineBreakMode="TailTruncation" />
            <Label FormattedText="{Binding RequestNumberFormatted}"
                   LineBreakMode="TailTruncation" />
            <Label FormattedText="{Binding PhaseFormatted}"
                   LineBreakMode="TailTruncation" />
            <Label FormattedText="{Binding SiteIdFormatted}"
                   LineBreakMode="TailTruncation" />
            <Label FormattedText="{Binding LocationFormatted}"
                   LineBreakMode="TailTruncation" />
        </StackLayout>

        <controls:TintedCachedImage
            Grid.Column="3"
            Grid.Row="0"
            Source="arrow.png"
            HorizontalOptions="Center"
            VerticalOptions="Center"
            TintColor="{Binding Phase, Converter={StaticResource ProjectPhaseToColorConverter}, ConverterParameter={Binding HasAlert}}"
            InputTransparent="True"
            IsVisible="{Binding IsBusy, Converter={StaticResource InverseBoolConverter}}" />

        <ActivityIndicator Grid.Column="3"
                           Grid.Row="0"
                           IsVisible="{Binding IsBusy}"
                           IsRunning="{Binding IsBusy}" />
        <BoxView Grid.Column="0"
                 Grid.Row="1"
                 Grid.ColumnSpan="4"
                 HeightRequest="1"
                 HorizontalOptions="FillAndExpand"
                 Color="{xaml:ResxColor PrimaryDarkBlue}" />
    </Grid>
</ContentView>
```

**Page Load**
![one](https://user-images.githubusercontent.com/471626/32691804-7e97185c-c6ca-11e7-825d-0341b62c3977.png)

**Partial Scroll Down**
![two](https://user-images.githubusercontent.com/471626/32691803-7e4c8f8a-c6ca-11e7-8dec-4c9068ef39ae.png)

**After Scroll down and back to top**
![three](https://user-images.githubusercontent.com/471626/32691802-7de73a40-c6ca-11e7-97cd-6b0506db5860.png)

**Comment by ChaseFlorell** [comment] 2017-11-11 20:21
I also tried this in the codebehind to remove the binding... but it gives the same result.

```csharp
public partial class ProjectListTemplate
{
    public ProjectListTemplate()
    {
        InitializeComponent();
        ResetImage();
    }

    protected override void OnBindingContextChanged()
    {
        ResetImage();
        base.OnBindingContextChanged();
    }

    private void ResetImage()
    {
        var item = BindingContext as ProjectsTabItem;
        if (item == null)
            return;

        PhaseImage.Source = item.PhaseIcon;
    }
}
```

**Comment by daniel-luberda** [comment] 2017-11-12 01:50
- Does it work when you replace `CachedImage` with `Image`? 
- Could you give some examples of `PhaseIcon` binding values?

**Comment by ChaseFlorell** [comment] 2017-11-12 02:48
Hey @daniel-luberda, yes it's works with `<Image />`, I'm actually attempting to improve our scrolling performance by exactly swapping `<Image />` for `<forms:CachedImage />`

The PhaseIcon is set in the code behind like so.

**Comment by gmwilhelm** [comment] 2017-11-13 08:57
I'm getting the same behavior in a normal listview. 
It also doesn't display the placeholder image.
I upgraded from 2.2.20 and tested the following releases (all on Xamarin.Forms 2.5.0.75255-pre3):

2.2.20 works
2.2.21 works
2.2.22 works
2.2.23 doesn't work
2.2.24-pre-605 doesn't work
2.2.24 doesn't work

so the last version where i get the expected behavior is the 2.2.22

**Comment by daniel-luberda** [comment] 2017-11-13 14:44
@gmwilhelm Thanks for the info. So it looks like fast renderer is a problem.

**Comment by daniel-luberda** [comment] 2017-11-13 15:07
Should be fixed now, thanks! :)

**Closed by daniel-luberda** 2017-11-13 15:07 UTC

**Comment by ChaseFlorell** [comment] 2017-11-13 17:17
@daniel-luberda  Is this enough of a change to merit a new patch release (or at least pre-release)?

**Comment by daniel-luberda** [comment] 2017-11-13 17:20
Yes, I want to fix issue 808 and release next stable today.

**Comment by ChaseFlorell** [comment] 2017-11-13 20:46
@daniel-luberda, that last update works, ty
