### ISSUE TITLE
[XF] Something wrong with CachedImage.AspectFill in 2.2.25 with 420dpi in Android

### ISSUE THREAD

**Issue by JTOne123** [luberda-molinet/FFImageLoading#830] opened 2017-11-28 10:44 UTC
After updating from 2.2.20 to 2.2.25, I've occurred an issue with AspectFill at 420dpi (it's Nexus 5X), I guess, something wrong with clipping of image.

Also, I've checked 560dpi and the same issue found. 

Typical dpi like l,m,h,xx works fine
I've tested it on Android 5, 6, 8

The image was not clipped and fill the bottom margin and placed under neighboring image
![image](https://user-images.githubusercontent.com/3457140/33315278-ed01ed28-d438-11e7-94e0-ee2f0b79a7d5.png)

The correct one, the image was clipped and we can see the bottom margin
![image](https://user-images.githubusercontent.com/3457140/33315659-fa255ea8-d439-11e7-8add-b6ef6bc42eed.png)

**Comment by daniel-luberda** [comment] 2017-11-29 23:19
It's not FFImageLoading but Xamarin.Forms issue when fast image renderers are used. You can disable fast renderer with `CachedImageRenderer(false). Did you try it?

**Comment by JTOne123** [comment] 2017-11-30 14:40
Yes, it is fastrenderers

Thank you for the hint, how I can disable it.

What do you think about this workaround?
            var supportedFastRenderersDpi = new[] {
                DisplayMetricsDensity.Default,
                DisplayMetricsDensity.Low,
                DisplayMetricsDensity.Medium,
                DisplayMetricsDensity.High,
                DisplayMetricsDensity.Xhigh,
                DisplayMetricsDensity.Xxhigh,
                DisplayMetricsDensity.Xxxhigh
            };            CachedImageRenderer.Init(supportedFastRenderersDpi.Contains(Resources.DisplayMetrics.DensityDpi));

Is it crazy?

**Comment by daniel-luberda** [comment] 2017-11-30 14:52
> You can disable fast renderer with CachedImageRenderer(false)

> Is it crazy?

It's Xamarin.Forms issue, it should be fixed IMO. I don't know if there's a Xamarin.Forms bugzilla entry for that. Maybe they have some workarounds for that :)

**Closed** 2017-11-30 14:52 UTC
Labels: Android, Xamarin.Forms

**Comment by daniel-luberda** [comment] 2017-11-30 14:54
When you replace `CachedImage` with `Image` (with fast renderers flag) the same behaviour exists:)

**Comment by JTOne123** [comment] 2017-11-30 14:55
Did you the issue about that in xbugzilla? Maybe we need to create it?

**Comment by daniel-luberda** [comment] 2017-11-30 14:59
I didn't time to do it yet. It would be great if you could create it. There are similar issue here: 

- https://github.com/luberda-molinet/FFImageLoading/issues/824
- https://github.com/luberda-molinet/FFImageLoading/issues/824#issuecomment-346177328

**Comment by JTOne123** [comment] 2017-11-30 15:15
I guess I have found this issue on xbugzilla

https://bugzilla.xamarin.com/show_bug.cgi?id=58048

**Comment by daniel-luberda** [comment] 2017-11-30 15:18
> Status: | RESOLVED FIXED

Nice catch! Looks like it should be reopened.

**Comment by daniel-luberda** [comment] 2017-11-30 15:21
> Note: Using IsClippedToBounds="true" on a nested StackLayout in the demo project resolves the problem, but this was not required before XF 2.3.5 and don't want to assume this is a fix (may be a workaround).

**Comment by JTOne123** [comment] 2017-11-30 15:23
yes, I need time to try and delete my super duper cool workaround :)

**Comment by JTOne123** [comment] 2017-11-30 16:23
Yes, it helps. This workaround is much better :)

**Comment by Nico04** [comment] 2018-06-06 15:09
Unfortunately I can reproduce this old issue with all latest packages installed (XF v3.0 & FFImageLoading v2.4.1) : With AspectFill, on Android, image is not cropped (but on some cases, with same image, it actually work...)
My current workaround is to embed it in a Frame with IsClippedToBounds=true.

**Comment by daniel-luberda** [comment] 2018-06-08 16:45
@Nico04 Could you make repo so I could fix it?

**Comment by Nico04** [comment] 2018-06-14 08:16
Unfortunately my code is private, but I'll make a small project trying to reproduce the issue soon, thanks.

**Comment by Nico04** [comment] 2018-06-14 16:58
I've build a sample project to show and test the bug :
https://github.com/Nico04/FFImageLoadingSample

I've tried several cases, some work and some don't.
Case that doesn't work :
1/ FFImageLoading in a **SfListView** (SyncFusion ListView component)

Cases that work great :
A/ FFImageLoading in a ListView (Xamarin.Forms component)
B/ Image (Xamarin) in a **SfListView** 
C/ FFImageLoading in a Frame in a **SfListView**

So the problem is an association of FFImageLoading & **SfListView**.

Do you have any idea ?
I will send this repo to the SyncFusion team too.

**Comment by daniel-luberda** [comment] 2018-06-14 17:01
Do you use fast renderer? (`CachedImageRenderer.Init` param)

**Comment by Yuvaraj-007** [comment] 2018-06-19 06:35
Hi Nico04,

    I think the following workaround is working fine for you. Can you check this.

```
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity 
{ 
    FFImageLoading.Forms.Platform.CachedImageRenderer.Init(false); 
}
```

**Comment by Nico04** [comment] 2018-06-19 07:10
Yes I use fast renderer, setting this to false will not impact performances ? If so, I think I would prefer the "Frame" fix no ?

**Comment by Yuvaraj-007** [comment] 2018-06-19 09:37
I didn't accurately know it is affect performance or not, But I checked the sample working fine for this workaround. If use fast renderer then pass argument as false to skip the image height problem.
` FFImageLoading.Forms.Platform.CachedImageRenderer.Init(false);`

**Comment by Nico04** [comment] 2018-06-22 13:31
Hello,

Thank you for your answer.
Unfortunately what you provide is a workaround that lower performances (which is still great though), not a fix nor a real solution.

Do you have an idea on a solution ?
I've told the same to the SF team, maybe it's on their side...

Thanks.

**Comment by daniel-luberda** [comment] 2018-06-22 13:37
Fast renderers are not enabled by default in Xamarin.Forms. You must explicitly enable it with `Forms.SetFlags("FastRenderers_Experimental");` - so maybe SF Team doesn't test their controls with fast renderers? It may be also a XF fast renderer bug too. I don't think it's related to FFImageLoading.

**Comment by Nico04** [comment] 2018-06-22 13:48
Nice to know, I didn't know it was an experimental feature.
So I will wait until it is stable. Thanks !
