### ISSUE TITLE
[Question] - Toolbar Icon sample (svg)

### ISSUE THREAD

**Issue by dazinator** [luberda-molinet/FFImageLoading#950] opened 2018-02-22 14:44 UTC
### Description

Are there any samples that show how to use an SVG icon for an Xamarin.Forms ToolbarItem?
I am trying various things but so far haven't been successful.

**Comment by daniel-luberda** [comment] 2018-02-26 13:40
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/913

**Closed by daniel-luberda** 2018-02-26 13:40 UTC
