### ISSUE TITLE
Unable to apply only the GrayscaleTransformation 

### ISSUE THREAD

**Issue by micheltol** [luberda-molinet/FFImageLoading#264] opened 2016-06-29 10:06 UTC
Hi,

 first of all thanks for making and supporting this project.
I have a weird issue with the GrayscaleTransformation.

Via a converter I am applying in Xamarin Forms certain transformations.

```

    public class BoolPropertyToTransformationConverter : IValueConverter
    {
        public static IList<ITransformation> ActiveTransformations = new List<ITransformation> ();

        /* We rotate 180 degrees -> Make it gray and rotate it back 180 degrees because of an issue in the library. Fixed an issue for the HTC ONE M8 testing phone*/
        //public static IList<ITransformation> InactiveTransformations = new List<ITransformation> { new RotateTransformation(180, true, false), new GrayscaleTransformation(), new RotateTransformation(180, false, false) };

        public static IList<ITransformation> InactiveTransformations = new List<ITransformation> { new GrayscaleTransformation() };


        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            // Return false if value is not a bool or false, true if bool and true
            return (value is bool && (bool)value) ? ActiveTransformations : InactiveTransformations;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```

Above code works on for example an Samsung S7, it doesn;t work on a HTC One M8.

if I replace 
`public static IList<ITransformation> InactiveTransformations = new List<ITransformation> { new GrayscaleTransformation() };` 

with the following line:
`public static IList<ITransformation> InactiveTransformations = new List<ITransformation> { new RotateTransformation(180, true, false), new GrayscaleTransformation(), new RotateTransformation(180, false, false) };`

it works.

Used packages:
  package id="Xamarin.FFImageLoading" version="2.1.6-pre-96" targetFramework="portable45-net45+win8+wpa81" 
  package id="Xamarin.FFImageLoading.Forms" version="2.1.6-pre-96" targetFramework="portable45-net45+win8+wpa81" 
  package id="Xamarin.FFImageLoading.Transformations" version="2.1.5" targetFramework="portable45-net45+win8+wpa81" 
  package id="Xamarin.Forms" version="2.3.0.49" targetFramework="portable45-net45+win8+wpa81"

Am I doing something wrong what by accident works on the S7?

**Comment by daniel-luberda** [comment] 2016-07-04 15:46
That's a really tricky one. I cannot reproduce it as I don't have `HTC One M8` device. Any ideas what could cause this?

**Comment by micheltol** [comment] 2016-07-04 19:37
To be honest; wouldn't have a clue.  
It is properly somewhere in the colorMatrix; cause if I remeber correctly I couldn't transform the image to sepia either.

I'll validate that in the morning.

**Comment by daniel-luberda** [comment] 2016-07-05 01:12
@micheltol Ok, waiting for some info. Did you set `TransparencyEnabled` to `true` or `false`?

**Comment by ckrempp91** [comment] 2016-07-05 15:17
Are you using png files with transparency? That was the problem in our case when the all of the color transformations did not work. Try using the latest pre-release version, it should include the fix to ensure that those types of images will transform correctly.

**Comment by daniel-luberda** [comment] 2016-09-06 03:18
I'll close this as I cannot reproduce it.

**Closed by daniel-luberda** 2016-09-06 03:18 UTC
Labels: Android, help wanted
