### ISSUE TITLE
CachedImageRenderer is not available for registration in .NET Standard

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#910] opened 2018-01-20 16:11 UTC
### Steps to Reproduce
- Install VS2017 15.5.3
- Create a blank Xamarin.Forms 2.5.0.122203 app with .NET Standard option
- Install FFImageLoading 2.3.4 Nuget package
- Add `CachedImageRenderer.Init();` to `MainActivity` and `AppDelegate`
- Observe that `Forms` is not recognizable by VS when you import
   - FFImageLoading.Forms.Touch
   - FFImageLoading.Forms.Droid

### Expected Behavior

Need to be able to register `CachedImageRenderer` so `FFImageLoading` can be used.

**Comment by daniel-luberda** [comment] 2018-01-20 16:30
Hi @adrianknight89,

What .NET Standard version? FFImageLoading is already a .NET Standard library. Even our samples are .NET Standard projects. 


Nuspec files are also correct: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/Xamarin.FFImageLoading.Forms.nuspec.template#L57-L60

**Comment by adrianknight89** [comment] 2018-01-20 18:23
Hmm. Not sure why I'm having this problem.

![screenshot 1](https://user-images.githubusercontent.com/16855542/35186626-89c7a91e-fddc-11e7-9791-843624cea914.png)

![capture](https://user-images.githubusercontent.com/16855542/35186633-a1e7d88e-fddc-11e7-8b41-4dba78512ace.PNG)

**Comment by 207713** [comment] 2018-01-25 12:51
@daniel-luberda I just have the exact same problem, we are using netstandard 2.1 though, could it be the issue?

**Comment by chowarth** [comment] 2018-01-25 20:23
Not sure if this is related or not. I created a completely new Prism.Forms v7 based project which uses a .netstandard 2.0. When trying to get FFImageLoading to work I noticed that after adding the Xamarin.FFImageLoading.Forms v2.3.4 package no dependencies had been installed. After manually adding the dependencies to both the .netstandard 2.0 project and the Android project everything appears to be working correctly. So I had to manually add the following:
**.netstandard 2.0 project**

- Xamarin.FFImageLoading.Forms
- Xamarin.FFImageLoading


**Android project**

- Xamarin.FFImageLoading.Forms
- Xamarin.FFImageLoading
- Xamarin.Android.Support.Exif
- Xamarin.Android.Support.Annotations

I'm using:

- Visual Studio 15.5.4
- Xamarin 4.8.0.757 (7f9ec2a)
- Xamarin.Android SDK 8.1.3.0 (HEAD/ef47226b7)
- Xamarin.iOS / Mac 11.6.1.6 (6857dfc)

**Comment by 207713** [comment] 2018-01-26 09:21
@chowarth I can confirm this, just followed your method and it works! Thank you!

**Comment by AnatolyUA** [comment] 2018-01-28 18:22
Can confirm @adrianknight89  issue
.NET Standard 2.0 

Does FFImageLoading support .NET Standard 2.0?

**Comment by AnatolyUA** [comment] 2018-01-29 05:45
I downgraded FFImageLoading to 2.3.2 and it works fine. So there is no problem with .NET Standard 2.0 and there is something wrong with 2.3.4 version of FFImageLoading.

**Comment by daniel-luberda** [comment] 2018-02-26 10:41
Nuget specs didn't change between 2.3.2 and 2.3.4, IMO it's some kind of nuget cache issue. Here are current nuspec files. Do you see any issues there? 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/Xamarin.FFImageLoading.Forms.nuspec.template

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/Xamarin.FFImageLoading.nuspec.template

**Comment by daniel-luberda** [comment] 2018-02-26 12:32
BTW: FFImageLoading supports .NET Standard starting from 1.0

**Comment by AnatolyUA** [comment] 2018-02-27 12:22
Yes, I can't reproduce it on the project created from scratch, so it looks like Nuget / VS issue.

**Comment by daniel-luberda** [comment] 2018-03-02 09:02
I'll close this one as I cannot reproduce it on a new project. Please attach a repo if it's still happening.

**Closed by daniel-luberda** 2018-03-02 09:02 UTC
Labels: more info needed
