### ISSUE TITLE
TintTransformation => Make HexColor Bindable Property

### ISSUE THREAD

**Issue by mzhukovs** [luberda-molinet/FFImageLoading#883] opened 2018-01-02 04:58 UTC
### Description

I may be missing something, but 2 things regarding TintTransformation:
1) HexColor takes a string, so I can't use StaticResource Color types that I have defined in my App.xaml
2) I can't bind to HexColor

I think binding to HexColor would be a great enhancement. Right now, I have an app where I change the color of certain icons depending on status or the background (e.g. sometimes they are white in some views, in other views they are color-coded). Instead of having to actually create colored versions of the icon, I use TintTransformation to color my white icons the right color, but right now i have to hardcode that hex string color for HexColor.

Was hoping to be able to do something like this instead:

    <ffimageloading:CachedImage.Transformations>
        <fftransformations:TintTransformation HexColor="{Binding ConverterParameter={StaticResource GreenColor}, Converter={StaticResource ColorToHexColorStringConverter}}" EnableSolidColor="true"/>
    </ffimageloading:CachedImage.Transformations>

        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (parameter != null && parameter is Color)
                return ((Color)parameter).GetHexString();

            if (value != null && value is Color)
                return ((Color)value).GetHexString();

            return Color.White.GetHexString();
        }

        internal static string GetHexString(this Xamarin.Forms.Color color)
        {
            var red = (int)(color.R * 255);
            var green = (int)(color.G * 255);
            var blue = (int)(color.B * 255);
            var alpha = (int)(color.A * 255);
            var hex = $"#{alpha:X2}{red:X2}{green:X2}{blue:X2}";

            return hex;
        }

**Comment by daniel-luberda** [comment] 2018-01-02 14:54
> HexColor takes a string, so I can't use StaticResource Color types that I have defined in my App.xaml

It's because transformations are cross platform (not XF only) and we can't use XF types with them. We could create some Xamarin.Forms transformations wrapper, but I'll need to thing about it if it's possible at all. We could implement `INotifyPropertyChanged` in transformations and subscribe to any changes (forcing image to reload). Any other ideas?

**Comment by daniel-luberda** [comment] 2018-01-02 14:58
Also duplicate of #860

**Closed by daniel-luberda** 2018-01-02 14:58 UTC
Labels: enhancement
