### ISSUE TITLE
Request: Provide way to download & cache images without assigning to views

### ISSUE THREAD

**Issue by ahohns** [luberda-molinet/FFImageLoading#143] opened 2016-02-11 00:14 UTC
Is it possible to provide a way to download & cache an image (either disk, memory, or both) without assigning the image to a view? 

Use case example: We'd like to iterate through a list and call a method that downloads & caches an image from each item in the list. This is so the images are pre-cached and display quicker when scrolling for certain listviews within an app. 

Currently images are only loaded when the cell becomes visible which at times can provide a slower than ideal experience especially when the network link is slow.

**Comment by highplains** [comment] 2016-02-11 14:34
This would be handy

**Comment by dspacey89** [comment] 2016-02-11 15:15
+1

**Comment by andrewSvsg** [comment] 2016-02-12 07:32
+1

**Comment by c1rus** [comment] 2016-02-12 07:34
+1

**Comment by adrianknight89** [comment] 2016-02-14 16:57
I'd like to see this done too.

**Comment by daniel-luberda** [comment] 2016-02-18 13:52
We could have some helper method to do that, but in my opinion, we need to modify scheduler to support task priorities to avoid starvation of normal image loading tasks.

**Comment by daniel-luberda** [comment] 2016-02-23 20:19
@ahohns @highplains @dspacey89 @andrewSvsg @c1rus https://github.com/molinch/FFImageLoading/commit/74d161a5683bd9008aef8aa764eb9e8f7429f9a0 I added `DownloadImageAndAddToDiskCache`  helper method for a start. What do you think?

**Comment by highplains** [comment] 2016-02-23 20:49
Is there a way to check if the image has already previously been downloaded
first?

**Comment by daniel-luberda** [comment] 2016-02-23 20:51
Not currently, I could modify method to just download image if it's not in cache. What do you think?

**Comment by highplains** [comment] 2016-02-23 22:00
Ya that could work, can you return a value from the function that indicates whether the image exists in the cache when the function exits?

**Comment by daniel-luberda** [comment] 2016-02-23 22:35
@highplains Yes, I just commited that changes.

**Comment by highplains** [comment] 2016-02-23 22:57
nice any way to get that into a RC on nuget?

**Comment by daniel-luberda** [comment] 2016-02-23 23:14
RC2 nuget already released. Could you test it?

**Comment by highplains** [comment] 2016-02-23 23:17
ya ill give it a go tomorrow for sure

**Comment by highplains** [comment] 2016-02-23 23:26
What does the lib do if I'm downloading the same images in the background that the user is requesting while scrolling? Just out of curiosity.

**Comment by daniel-luberda** [comment] 2016-02-23 23:32
For now, image loading task prioritizing is not implemented (it's on a todo list), so basically it behaves just the same as other image downloads which use Views. I advice to insert `Task.Delay` call after each `	DownloadImageAndAddToDiskCacheAsync` for now to minimize its effect.

**Comment by daniel-luberda** [comment] 2016-02-26 14:00
Did anyone test it?

**Comment by highplains** [comment] 2016-03-03 21:15
Looking good so far!

**Comment by daniel-luberda** [comment] 2016-03-04 16:40
@highplains Thanks for testing! 

I want to modify that method, so the downloading would only work when no other image loading tasks are running. My idea is to: 

- Modify `ITaskScheduler` so it would expose `HasPendingTasks` property
- `DownloadBytesAndCacheAsync` (https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Shared/ImageService.cs#L373) will not be called until `HasPendingTasks = false`, wait otherwise.

What do you think about this approach?
@molinch

**Comment by highplains** [comment] 2016-03-04 16:52
In my app pictures are downloading frequently as the user scrolls, i would
still like to be "pre-downloading" pictures later in the list while that is
happening. Can you open it up as a options so we can choose?

**Comment by daniel-luberda** [comment] 2016-03-04 16:56
@highplains Sure, I think a simple method parameter, eg. `downloadOnlyWhenIdle = false` will be enough.

**Comment by molinch** [comment] 2016-03-08 07:15
IMO preloading images while there is ongoing work will kill performance.
As a result I am against such a parameter.

**Comment by joeforshaw** [comment] 2016-03-10 09:39
When I call `CachedImage.DownloadImageAndAddToDiskCacheAsync ()` it always returns false and doesn't appear to cache images. It still returns false if I delete the app and run my app from fresh, without any images cached.

Is there any setup that I need to perform to use `CachedImage.DownloadImageAndAddToDiskCacheAsync?`

**Comment by daniel-luberda** [comment] 2016-03-10 12:51
@joeforshaw  What version of nuget?

**Comment by joeforshaw** [comment] 2016-03-10 12:54
v0.2.7.1

**Comment by daniel-luberda** [comment] 2016-03-10 12:56
@joeforshaw Could you try 2.1.0-alpha1?

**Comment by joeforshaw** [comment] 2016-03-10 13:12
@daniel-luberda Just tried it out, the issue is still present in 2.1.0-alpha1.

**Comment by molinch** [comment] 2016-03-10 22:09
Just to let you know `CachedImage.DownloadImageAndAddToDiskCacheAsync()` will be removed in 2.1.0 and be replaced by a Fluent method like `Preload()` directly on TaskParameter.
It will be much more handy and will handle priority.

**Comment by daniel-luberda** [comment] 2016-03-11 05:33
@molinch There's no concept of TaskParameter on Xamarin.Forms, I think `CachedImage.DownloadImageAndAddToDiskCacheAsync()` would stay (we'll change only its internal implementation.

**Comment by molinch** [comment] 2016-03-16 22:22
@joeforshaw a new implementation for preloading has been pushed to master
We will deliver new alpha nugets soon

**Comment by joeforshaw** [comment] 2016-03-16 22:34
Roger that, thanks for letting me know.

**Comment by xPeKx** [comment] 2016-04-26 13:11
When we can expect this to be released?

**Comment by xPeKx** [comment] 2016-04-26 13:11
When we can expect nugets?

**Comment by molinch** [comment] 2016-04-29 18:51
@xPeKx @joeforshaw @ahohns   2.1 Alpha 2 nugets have been released and they contain the new `Preload`method.

Could you give it a try?

**Comment by xPeKx** [comment] 2016-05-04 10:16
It is working for me.

**Comment by owlstack** [comment] 2016-05-10 21:13
@xPeKx How are you calling your preload method and where would you typically make that call? In the view with the images or in app.cs? Thanks!

**Comment by molinch** [comment] 2016-05-11 05:25
@owlstack Just use standard API for it: https://github.com/luberda-molinet/FFImageLoading/wiki/API
For example: `ImageService.Instance.LoadUrl(urlToImage).Preload()`

**Comment by molinch** [comment] 2016-05-15 16:12
Closing since this is available in our release candidates

**Closed by molinch** 2016-05-15 16:12 UTC
Labels: enhancement

**Comment by tamifist** [comment] 2016-05-27 18:58
How I can use it from Xamarin.Forms shared code?

**Comment by molinch** [comment] 2016-05-27 19:14
@tamifist From anywhere you can call:
```c#
ImageService.Instance.LoadUrl(urlToImage).Preload();
```

**Comment by patook** [comment] 2017-02-10 19:09
@molinch @daniel-luberda is this broken on Forms? It's not longer compiling as of > 2.2.0. It works fine in individual iOS/Android projects but not in the PCL Forms.

ImageService.Instance.LoadUrl(value).Preload();

Error CS1955: The member `FFImageLoading.Work.TaskParameter.Preload' cannot be used as method or delegate (CS1955)

I also cannot find DownloadOnly

**Comment by patook** [comment] 2017-02-10 19:12
Oh nevermind, it looks like it's an extension method so I need to use FFImageLoading instead of doing FFImageLoading.ImageService...

**Comment by flamecrow** [comment] 2018-02-26 20:42
@patook Can you show me an example of how you got preload() to work in Xamarin Forms? I get the CS1955 error..
