### ISSUE TITLE
Border Size issue

### ISSUE THREAD

**Issue by stesvis** [luberda-molinet/FFImageLoading#1017] opened 2018-04-23 17:43 UTC
Here's an example of two circle images.
The first one is obtained with the **ImageCircle** plugin, and the second one with **FFImageLoading**.

With ImageCircle i set **BorderThickness="1"**, while with FFImageLoading i had to set **BorderSize="15"** to obtain the same border look (sorta).

Can you explain how the BorderSize works? How to convert BorderSize to the equivalent (standard) Thickness?

![image](https://user-images.githubusercontent.com/6062684/39143533-6a67ad82-46eb-11e8-814d-e225bc8c26f1.png)

**Comment by daniel-luberda** [comment] 2018-04-24 12:47
It's a duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/1012

Please read it for an explanation. Thanks.

**Closed by daniel-luberda** 2018-04-24 12:47 UTC
