### ISSUE TITLE
Xamarin Forms 2.2 support

### ISSUE THREAD

**Issue by lecnierfreeman** [luberda-molinet/FFImageLoading#182] opened 2016-04-18 20:43 UTC
@daniel-luberda Hi,

Sorry to say that in indeed it's a FFImageLoading issue, but I think is an easy one, since in this new pre-release version of Xamarin.Forms they moved to Xamarin.Android.Support.v4(and Friends) to version 23.1.1.1 all you need to do is just re-build the nugget packages with that version.

For confirming that it's a FFImageLoading I tried removing all packages from my project, install lates pre-release of Xamarin.Forms 2.2.0.5-pre2, install again all packages that I was using except FFImageLoading and try to build, and It succeeded, then Add FFImageLoading and try to build, it failed with the errors I posted before. 
After that I created a new project, installed Xamarin.Forms 2.2.0.5-pre2, build succeeded, install FFImageLoading and Failed again.
I was reading in the same post you point it out and people says they are having this issues with 3rd party libs that need to update their Xamarin.Android.Support.v4(and Friends) to version 23.1.1.1

Thank You

**Comment by daniel-luberda** [comment] 2016-04-18 21:06
@lecnierfreeman Thanks for the info. I didn't test alpha Xamarin.Forms yet. I'll give it a look soon.

**Comment by ryanherman** [comment] 2016-04-22 00:31
I can confirm and I just recompiled FFImageLoading.Forms.Droid w/ Forms 2.2.0.5-pre4 and all is back to normal.  I think I'm gonna wait for you guys to release on NuGet with the update.

Awesome Work!  Love this Plugin.

**Comment by adrianknight89** [comment] 2016-04-22 01:12
@daniel-luberda I'm using XF 2.2.0.23-pre4 and having the same issues. I have Android Support library 23.3.0.

**Comment by michaeldimoudis** [comment] 2016-04-27 23:50
Xamarin Forms 2.2.0 stable just got released, any chance you can get a new nuget package out so we can use the new forms build in Android? Thanks :)

**Comment by ArtemZelinsky** [comment] 2016-04-28 13:27
Have same errors, as above. Can not get it to work with latest stable Forms build on Android. Shows multiple "missing resource" errors

**Comment by alicint** [comment] 2016-04-28 15:17
Upgraded xamarin forms to version 2.2, I can't build, same issue as others.

**Comment by tobiasschulz** [comment] 2016-04-29 08:57
This is really urgent. 2.2 is a stable release now and it doesn't build with FFImageLoading.

**Comment by molinch** [comment] 2016-04-29 09:25
@daniel-luberda Is it fixed in master?

**Comment by timbrand** [comment] 2016-04-29 10:41
@molinch Yes, sort of. The XF packages aren't updated in the Master yet. But if you do update them and build, it's running fine.
Currently running the new compiled version on beta's on iOS and Android for about a week now, without problems.

**Comment by molinch** [comment] 2016-04-29 10:44
Thanks for the feedback @timbrand !
I'll do that then

**Comment by daniel-luberda** [comment] 2016-04-29 13:36
@molinch I'll fix that and release alpha nuget now.

**Comment by lecnierfreeman** [comment] 2016-04-29 14:23
Thank You, Thank You, Thank You, I've been waiting for this two weeks, couldn't build Android.

**Comment by daniel-luberda** [comment] 2016-04-29 14:29
FFImageLoading 2.1.0-alpha2 nuget with Xamarin.Forms 2.2.0.31 support released.

**Comment by krisrok** [comment] 2016-04-29 16:20
can confirm it works. 
but only after you add the references to the platform-specific project, too.

i'm pretty new to the xamarin-thing so i don't know if that's normal.

**Comment by adrianknight89** [comment] 2016-04-29 16:49
At the moment, I'm getting a weird

`Exception in thread "main"` error in COMPILETODALVIK

**Comment by molinch** [comment] 2016-04-29 18:36
@adrianknight89 TBH I don't know why you got this but it definitely seems to be a Xamarin or Android issue
Thanks for posting the solution! It will be useful in case somebody else gets it in the future.

**Comment by molinch** [comment] 2016-04-29 18:58
@krisrok Yes that's the normal scenario :)

**Comment by patook** [comment] 2016-04-29 21:15
I have done some testing over the past couple of hours. The XF2.2 version compiles/runs for me.

However, I am seeing some perf degradation in the alpha nugets compared to the original nugets. My observations:
1- Loading the images on start-up (from DiskCache I'm guessing) seems particularly slow as well. If I turn the app off/on there is always a long lag at the beginning until the images show up. This lag feels slower than what I had in the previous FF nugets.

2- Are the images loaded in a different order than before? Looks like some of the last ones now show up first. This could be what's causing the slowness perception.

Is this expected? Is it possible to revert to the "old" method of caching within this nuget?

**Comment by ravensorb** [comment] 2016-04-29 21:49
Does the latest build really depend on XF2.2? I have a lot of issues with XF 2.2 right now on Android so I am holding off on upgrading.

**Comment by molinch** [comment] 2016-04-29 21:51
@patook I created https://github.com/molinch/FFImageLoading/issues/188 for your issue it will be easier to continue there

**Comment by patook** [comment] 2016-05-04 18:12
FYI we have the latest version of FFImageLoading (compiled from source) in production for the past two days on iOS and things are stable.

**Comment by molinch** [comment] 2016-05-07 06:51
@daniel-luberda Can I let you answer @ravensorb's question?

**Comment by daniel-luberda** [comment] 2016-05-07 13:35
@ravensorb  Yes, It depends on it. I'll try to make two nugets on release "old Forms" and "new Forms" as those builds are not compatible.

**Comment by ravensorb** [comment] 2016-05-07 15:38
Interesting -- what changed that sets the hard dependency?

**Comment by daniel-luberda** [comment] 2016-05-07 15:39
Actually, Xamarin.Forms 2.2 (Android) itself, I'll try to investigate if we can do something about it to be independent of that.

**Comment by tobiasschulz** [comment] 2016-05-08 13:58
I don't think you can. If you use the android app compat packages, you have to set the nuget dependency to a specific version (just as Forms does). Or you could depend on a Forms version range (2.1.X or 2.2.X), which in turn would depend on a specific AppCompat version...

**Comment by daniel-luberda** [comment] 2016-05-08 14:53
@tobiasschulz  Thanks to @aritchie, we'll probably have this sorted out and be compatible with all XF versions in one package:

> remove resources.cs and edit your csproj. Remove <AndroidResgenFile>

**Comment by daniel-luberda** [comment] 2016-05-08 17:58
2.1.0-rc1 nuget released. As always, testers needed.

**Comment by molinch** [comment] 2016-05-08 19:30
@ravensorb @patook @adrianknight89 @krisrok @lecnierfreeman Could you please test the release candidate and tell us in case you find anything weird?
We would like to release it this as soon as possible.

Thanks !

**Comment by patook** [comment] 2016-05-08 19:50
@molinch The build I got from source has been in production on the iOS app store for over a week and is running perfectly. I have had zero crashes in the last 5,000 sessions with the 2.1 build (and XF2.2).

**Comment by michaeldimoudis** [comment] 2016-05-09 12:45
Hmmm this is really bugging me, I am having absolutely major issues with 2.1.0-rc1 with xamarin forms 2.2. Images aren't getting cached. I have them in a list view, they get downloaded each time. When I click on the cell to go to next page, the same image is again displayed in the content page, and it's getting re downloaded. I close the app, turn off net, open the app, and images are not there, error place holder is shown. Also in my list view  scrolling through the list, you can see other images briefly be loaded where they shouldn't be.

My bindings are in the XAML
            <ffimageloading:CachedImage
                WidthRequest="100"
                HeightRequest="100"
                DownsampleToViewSize="true"
                DownsampleUseDipUnits="true"
                Aspect="AspectFill"
                LoadingPlaceholder="ImageLoading.png"
                ErrorPlaceholder="ImageLoadingError.png"
                Source="{Binding FirstImage}" />

**Comment by daniel-luberda** [comment] 2016-05-09 12:48
@michaeldimoudis Did you try the newest nuget (RC1)? Is it on Android/iOS? I'll need more details.

**Comment by michaeldimoudis** [comment] 2016-05-09 12:49
Yea I'm on RC1. It's iOS. I'll fire up Android and see if it's the same...

**Comment by michaeldimoudis** [comment] 2016-05-09 12:57
@daniel-luberda it's fine on Android. Just iOS is my issue... I'll keep trying some things, cleaning, resetting sim, etc.

**Comment by daniel-luberda** [comment] 2016-05-09 13:00
@michaeldimoudis It has to be something specific to your project. Do you empty any caches? Do you preserve caches between app deploys?

**Comment by michaeldimoudis** [comment] 2016-05-09 13:28
@daniel-luberda nop, just a stock standard implementation. I init it in AppDelegate, and just call CachedImage where I need to. The only non standard thing is my ImageService initialize which is this. This all worked as expected before I upgraded forms and FFImageLoading nuget packages.

            ImageService.Instance.Initialize(new Configuration
            {
                FadeAnimationDuration = 50, 
                HttpClient = new HttpClient (new AuthenticatedHttpImageClientHandler (() => new SecureStorage ()))
            });

It is so weird, that if I load the image in the ListView, and then go to another page with the same image, it re downloads it arrrgghh :(

I'm on the beta channel of Xamarin Studio. If I have time later I might go to the previous branch with the stable nuget, and see if this anomaly keeps happening... I pretty much just updated the nuget package, and converted my ListView to have DataTemplateSelector and that's all...

**Comment by michaeldimoudis** [comment] 2016-05-09 13:41
Ok there is something weird going on with FFImageLoading 2.1.0 on iOS, I restored my project back to master with xamarin forms 2.0 and FFImageLoading 2.0.7.1, worked as expected, cached when offline as expected. I then only updated FFImageLoading to 2.1.0 rc1 and images don't get cached. Obviously I let the app re download the images on 2.1.0, closed app and turned off my wifi, opened app, and all images were now broken. I did get this error in the output window once, not sure if it's much help: WARNING: An HttpWebRequest was added to the ConnectionGroup queue because the connection limit was reached.

It's approaching midnight where I am, so I'll leave this here, if you need me to do any other debugging let me know.

**Comment by molinch** [comment] 2016-05-09 18:21
You are right I confirm the issue. I'm working on it.
Many thanks for reporting it 👍

**Comment by patook** [comment] 2016-05-09 18:46
@molinch is this something that was newly introduced in the last week? I have last week's build of 2.1 from source and am not seeing such an error (I think).

**Comment by molinch** [comment] 2016-05-09 18:48
@patook the bug is only on iOS

**Comment by molinch** [comment] 2016-05-09 19:42
@michaeldimoudis fixed in git, should be available soon via nuget

**Comment by michaeldimoudis** [comment] 2016-05-10 05:14
@molinch no probs, glad this was caught now not later :) Nuget isn't updated yet, you get an ETA for that? Cheers.

**Comment by patook** [comment] 2016-05-11 23:01
Hi @molinch are the RC2 nugets up?

**Comment by krisrok** [comment] 2016-05-12 07:47
@patook you can look it up yourself at https://github.com/luberda-molinet/FFImageLoading
just scroll down to the version history. the topmost entry is the newest version available on nuget.

**Comment by molinch** [comment] 2016-05-12 07:53
Unfortunately Daniel's PC is broken now: some liquid fell on it.
So we will need to wait 1 or 2 additional days before having the final nuget.
Meanwhile you can use, as krisrok said, the prerelease nugets.

**Comment by daniel-luberda** [comment] 2016-05-15 14:02
Released 2.1.0-rc2 release, feel free to test it as it's stable candidate. If you're using 2.1.0-rc1 on iOS, it's very important to update as that version has a bug that causes caching to be disabled. Thanks.

**Comment by ravensorb** [comment] 2016-05-15 17:28
i am still hitting the corrupt data error after loading the latest version.

```
Unable to read package from path 'Xamarin.FFImageLoading.Forms.2.1.0-rc2\Xamarin.FFImageLoading.Forms.2.1.0-rc2.nupkg'.
  File contains corrupted data.
```

**Comment by NVentimiglia** [comment] 2016-05-18 06:14
+1

**Comment by molinch** [comment] 2016-05-19 06:18
2.1 released which supports new XF and fixes corrupted package issue.
Many thanks @ravensorb for your help and debugging!

**Closed by molinch** 2016-05-19 06:18 UTC
Labels: Xamarin.Forms
