### ISSUE TITLE
Crash on Xamarin Forms ListView with CachedImage: 'Cannot access a disposed object'

### ISSUE THREAD

**Issue by mattjennings** [luberda-molinet/FFImageLoading#475] opened 2017-02-02 05:08 UTC
I have a list of about 100 objects all with an image loaded asynchronously with the <forms:CachedImage> XAML property. The ListView has the CachingStrategy set to "RecycleElement". If it's set to RetainElement then there are no problems but performance drops.

Here's how to produce the problem: on Android if I scroll really fast down the list it'll eventually throw a "Cannot access a disposed object" exception. If I scroll slowly and load all the images so that they're cached, this no longer happens because it loads from the cache. This doesn't happen on UWP and I've yet to try it on iOS.

At this point I assume the CachedImage is sending out an HTTP request and having it come back to the cell when it's been disposed/recycled. I've tried running CachedImage.Cancel() just about everywhere I could (such as when the cell leaves the screen or reloads the data), but that doesn't seem to do anything.

I'm open to any suggestions or further bug testing if you need.

**Comment by slarti-zak** [comment] 2017-02-17 09:56
I'm getting the same error with 2.2.8 with the same setup. Images in a RecyclerView on Android -> scrolling very fast -> crash 'Cannot access a disposed object'.

**Comment by daniel-luberda** [comment] 2017-02-24 15:53
@mattjennings @slarti-zak Does image load correctly afterwards? Or maybe application crashes?

**Comment by slarti-zak** [comment] 2017-02-26 15:58
The result is that the application crashes with the message 'Cannot access a disposed object'. I am currently trying to set up a test project to reproduce the bug.

While I was not yet able to reproduce this bug, I have produced another bug. Using a _MvxImageLoadingView_ with an applied _CircleTransformation_ in a _MvxRecyclerView_ sometimes causes the transformation to not be applied. (See bugged images at the end.)

[You may find the test project here](https://github.com/slarti-zak/ffimageloading_recyclingcrash/tree/aa871c3d1916d50c7c0b12e881b3cbc0d8e160e1). The bug occurs when scrolling through the images (up and down, querying the same image multiple times). It seems that a half finished version of the image (loading done, transformation not) is put into the cache when the load task of the image view gets cancelled because the image view gets recycled in the list.

The bug is easier to reproduce with a slower internet connection (not too slow, images still have to load). You can also see that sometimes the images are in the wrong order (incorrect image loaded).

There is no exception thrown in the log.

Images:
![transformationnotapplied](https://cloud.githubusercontent.com/assets/13180178/23341136/44e4b112-fc42-11e6-8c11-5452d5e29b25.png)
![transformationnotapplied-2](https://cloud.githubusercontent.com/assets/13180178/23341272/6fa45ed2-fc44-11e6-8dd4-2517c9a10ef2.png)
![transformationnotapplied-3](https://cloud.githubusercontent.com/assets/13180178/23341274/7253dc8e-fc44-11e6-8c03-01433623ce97.png)

**Comment by daniel-luberda** [comment] 2017-02-28 18:23
The "wrong order" issue may be related to this: https://github.com/luberda-molinet/FFImageLoading/issues/506. Thanks to @EGoverde - it's fixed now.

As to the rest I'll try to debug it soon.

**Comment by daniel-luberda** [comment] 2017-02-28 18:46
The "wrong order" issue may be related to this: https://github.com/luberda-molinet/FFImageLoading/issues/506. Thanks to @EGoverde - it's fixed now.

As to the rest I'll try to debug it soon.

**Comment by slarti-zak** [comment] 2017-02-28 20:03
Glad to hear. I will try to get a crashing example, with regards to the issue topic, ready on the weekend. I have already experienced it within the example project but the current state seems to be working. Not sure yet what causes the crash.

**Comment by daniel-luberda** [comment] 2017-04-29 14:49
Hi @slarti-zak, 

It took a while (I've been quite busy), but I made entirely new `MvxCachedImageView` which is far superior than old depreciated `MvxImageLoadingView`. 

There are also samples for it: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.MvvmCross.Sample

The issue you described there is fixed when using it too. It's available in the latest prerelease package.

![screenshot_1493477037](https://cloud.githubusercontent.com/assets/13569983/25556373/7363b51c-2cfb-11e7-9a18-f57771d15b59.png)

Thanks you for your example, it helped a lot!

**Closed by daniel-luberda** 2017-04-29 14:49 UTC
Labels: more info needed

**Comment by slarti-zak** [comment] 2017-05-02 19:39
That's Great! I had yet to get back into this but will now try out (try to break) the new stuff.

**Comment by mattrichnz** [comment] 2017-06-26 14:34
We noticed this same issue last week when scrolling a rather large ListView. When is the next stable release of the package expected to be released?
