### ISSUE TITLE
CachedImage will Change the LoadingPlaceholder Proportion before Url Image Shown

### ISSUE THREAD

**Issue by ChocolateTan** [luberda-molinet/FFImageLoading#972] opened 2018-03-13 09:02 UTC
Hi, FFImageLoading is easy to use. I try to add LoadingPlaceholder is ok. But when image is finish to load, LoadingPlaceholder will be change the proportion, before url image shown.
```
var image = new CachedImage()
                {
                    HorizontalOptions = LayoutOptions.FillAndExpand,
                    //VerticalOptions = LayoutOptions.StartAndExpand,
                    //VerticalOptions = LayoutOptions.Fill,
                    WidthRequest = Application.Current.MainPage.Width,
                    HeightRequest = Application.Current.MainPage.Width / 1.8,
                    CacheDuration = TimeSpan.FromDays(30),
                    DownsampleToViewSize = true,
                    RetryCount = 0,
                    RetryDelay = 250,
                    Aspect = Aspect.AspectFill,
                    //TransparencyEnabled = false,
                    //TransformPlaceholders = false,

                    LoadingPlaceholder = "resource://CodeXamarin.asserts.images.imageholder.jpg",
                    ErrorPlaceholder = "resource://CodeXamarin.asserts.images.imageholder.jpg",
                    //Source = "https://1.bp.blogspot.com/-vmav3oXKkoI/WOseQDXUOZI/AAAAAAAAfQw/vxKcRzkwBJIek5sdlTxdzr6-THiQsKLAwCLcB/s1600/ScreenShot_20170410135502.png"
                };
```
`image.SetBinding(CachedImage.SourceProperty, "cover_image_basic.url");`

**Comment by daniel-luberda** [comment] 2018-03-20 14:44
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/353

**Closed by daniel-luberda** 2018-03-20 14:44 UTC
