### ISSUE TITLE
image stop showing after upgrading XF and NuGet 2.3.2 (after 2.2.22)

### ISSUE THREAD

**Issue by ibrahimdarahem** [luberda-molinet/FFImageLoading#884] opened 2018-01-02 11:04 UTC
### Description

I Use: 
* Visual Studio 2017
* Xamarin Forms 2.5.0.121934
* 

### Steps to Reproduce

This Simple Page in New (PCL) project

    <ContentPage.Content>
        <StackLayout>
            <Image Source="icon.png"/>
            <ffimageloading:CachedImage Source="icon.png"/>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

### Expected Behavior

Till  Ver 2.2.22  Showing the 2 Images correctly 

### Actual Behavior

After Ver 2.2.22  not Showing cashedimage (showing only the standard image) 

### Basic Information

- Version with issue: 2.3.2
- Last known good version: 2.2.22
- Platform: Visual Studio 2017

**Comment by daniel-luberda** [comment] 2018-01-02 13:38
Somehow you nuget cache / project files cache is probably corrupted. Please remove all `bin` / `obj` folders, reinstall all nuget packages etc

**Comment by ibrahimdarahem** [comment] 2018-01-03 07:15
I did that, and all other probable fixes, but no way.
any way, as I said, it works fine when I downgrade to ver 2.2.22  (2.2.23 or later not working).

So, I think there may be a "bug" needs a fix in the component,
Note:  I faced this error when trying with android (I use Xamarin Forms) but I did not try ios or win.

**Comment by daniel-luberda** [comment] 2018-01-03 14:41
I'll need a repo project as I am not aware of any issues about that and can't reproduce it.

**Comment by daniel-luberda** [comment] 2018-01-03 14:42
Also please make cure you call `CachedImageRenderer.Init()` as described in our wiki.

**Comment by EmilAlipiev** [comment] 2018-01-03 21:06
yes I call it like tha`t   FFImageLoading.Forms.Droid.CachedImageRenderer.Init(enableFastRenderer:true);`
This version looks like solving all the problems above. thank you for you quick and great support. i close this ticket.

**Closed** 2018-01-04 15:30 UTC
Labels: more info needed, question
