### ISSUE TITLE
Could not load type 'FFImageLoading.Views.ImageViewAsync' from assembly 'FFImageLoading.Platform

### ISSUE THREAD

**Issue by gruan01** [luberda-molinet/FFImageLoading#317] opened 2016-09-19 17:25 UTC
Hello, 
I'm using FFImageLoading 2.1.7 From Nuget,
I have add the following to Activity:

FFImageLoading.Forms.Droid.CachedImageRenderer.Init();

before 
global::Xamarin.Forms.Forms.Init(this, bundle);

But I get the following error :

~~~
09-20 01:21:11.234 I/MonoDroid( 4458): System.TypeLoadException: Could not load type 'FFImageLoading.Views.ImageViewAsync' from assembly 'FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
09-20 01:21:11.234 I/MonoDroid( 4458):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) [0x00011] in <filename unknown>:0 
09-20 01:21:11.234 I/MonoDroid( 4458):   at (wrapper dynamic-method) System.Object:ee3923ab-f62a-4173-812d-5746c236a6ab (intptr,intptr,intptr)
~~~

What's wrong ?
Thanks.

**Comment by adrianknight89** [comment] 2016-09-19 22:07
See https://github.com/luberda-molinet/FFImageLoading/issues/313

**Comment by daniel-luberda** [comment] 2016-09-21 15:14
Duplicate of #313

**Closed by daniel-luberda** 2016-09-21 15:14 UTC

**Comment by daniel-luberda** [comment] 2016-09-21 20:06
FFImageLoading 2.1.8-pre-146 nuget which contains discussed issues released.
