### ISSUE TITLE
iOS TintTransform not working while Android and UWP does.

### ISSUE THREAD

**Issue by dberroa** [luberda-molinet/FFImageLoading#901] opened 2018-01-12 02:31 UTC
### Description

I'm trying to tint my iOS cache image via the TintTransformation via code. Using Xamarin Forms.

### Steps to Reproduce

Create an image in iOS via xaml and pass a reference to the image to your view model. Then in the view model change the tint.

I set the init method in appdelegate:

```
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            //Init the FFImage renderer.
            CachedImageRenderer.Init();

            return base.FinishedLaunching(app, options);
        }
```

And set the image transforms on button tap with:

               
                //Set the tint of the aimer image.
                AimerImage.Transformations = new List<ITransformation> {
                    new TintTransformation {
                        HexColor = AimerColor,
                        EnableSolidColor = true
                    }
                };
              

### Expected Behavior

The color should change.

### Actual Behavior

It stays white (my image defaulted is white).

### Basic Information

- Version with issue: 2.3.4
- Platform: iOS

**Comment by daniel-luberda** [comment] 2018-01-12 09:57
- Make sure you have `Xamarin.FFImageLoading.Transformations` package installed in **your platform specific project** too. 
- Sometimes linker removes transformations, reference them by calling `var ignore = typeof(TintTransformation)` in `AppDelegate.cs`

**Comment by dberroa** [comment] 2018-01-13 02:21
The package is installed in all four projects being the .NET standard one, iOS, Android, and UWP.

I added the var ignore line in appdeletegate under the init and still a clean and rebuild of the project and still have the same issue. The iOS image isn't changing tint but Android and UWP are.

**Comment by Niels-Wosylus** [comment] 2018-01-14 13:11
I am experiencing the exact same issue using Xamarin Forms. It works perfectly on Android, but my images stay white on iOS. I have all packages installed in all my platform specific projects as well, and I also tried adding the var ignore line to my AppDelegate.cs.

**Comment by dberroa** [comment] 2018-01-15 23:28
@Niels-Wosylus What about UWP for you?

**Comment by Niels-Wosylus** [comment] 2018-01-16 12:14
@dberroa I haven't tried UWP, I usually only work with Android and iOS

**Comment by dberroa** [comment] 2018-01-17 02:36
@daniel-luberda Any ideas on why this may be? I have the iOS app on hold as I'm figuring this out.

**Comment by dberroa** [comment] 2018-01-27 04:26
@Niels-Wosylus Have you found a way to get this working?

**Comment by daniel-luberda** [comment] 2018-03-29 13:45
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/939 - let's continue there.

**Closed by daniel-luberda** 2018-03-29 13:45 UTC
Labels: Xamarin.Forms, iOS, question
