### ISSUE TITLE
Issue loading images from resources iOS 2.2.5

### ISSUE THREAD

**Issue by kamekjay** [luberda-molinet/FFImageLoading#430] opened 2016-12-27 17:31 UTC
Hi guys i have a little problem with 2.2.5 version...i'm currently working on a project with xamarin forms (android / iOS) and it's all fully working on FFIL 2.2.4. The problem is loading images from resources folder in iOS platform: using cachedimage with the name of the images in the source attribute as string. None of the images loaded with this method is working :( the problem is that it doesn't work only on iOS platform, Android is fine. Am i missing some settings? Using this loading method on 2.2.4 everything is working fine... please help me

**Comment by alanspires** [comment] 2016-12-27 17:35
This is already fixed in the pre-release nugets. You should update to those.

**Comment by kamekjay** [comment] 2016-12-27 17:37
@alanspires thank you for the info...i'll try to update to pre release ;)

**Comment by daniel-luberda** [comment] 2016-12-28 16:11
@kamekjay Yes, it should be fixed in a prerelease nuget. Thanks @alanspires

**Comment by Jelle-elaut** [comment] 2017-01-03 15:29
Hello! At the moment I have a simular issue on iOS. Everything is working fine on Android, but I can't seem to load images on iOS. Neither with version 2.2.4, 2.2.5 or the pre-release version of 2.2.6 :/

**Comment by daniel-luberda** [comment] 2017-01-03 15:31
@Jelle-elaut Could you give more details?

**Comment by Jelle-elaut** [comment] 2017-01-03 15:40
@daniel-luberda thanks for the quick response. I'm afraid I can't give a lot more useful information. I have this piece of code which works perfectly on Android, but doesn't load any image on iOS.

`<forms:CachedImage
                x:Name="FirstCachedImage"
                Source="{Binding FilePaths[0]}"
                DownsampleToViewSize="True"
                Grid.Column="0"
                Grid.Row="0"
                Aspect="AspectFill"
                BackgroundColor="{StaticResource PhotoPickerPlaceholderColor}" />`

The FilePath is correctly working because everything works like it should when I replace the CachedImage with a regular image. I got exactly the same behavior on version 2.2.4, 2.2.5 and 2.2.6.

**Comment by daniel-luberda** [comment] 2017-01-03 15:42
@Jelle-elaut Could you write more details about: 
 - How you have those files included in iOS project?
 - Give some paths examples? eg. "file1.png", etc

**Comment by kamekjay** [comment] 2017-01-03 15:50
@daniel-luberda @Jelle-elaut Hi guys! I want you to know that when @alanspires told me to update to prerelease this fixed my problem with image loading on iOS platform. Now i've just updated to 2.2.6 and it works well on both platfoms. So i think that it's a different problem from what i've experienced.

**Comment by Jelle-elaut** [comment] 2017-01-03 15:53
@daniel-luberda These are files loaded from the camera/gallery of the device. Example of the paths: 

- "/var/mobile/Containers/Data/Application/FB3E4E5A-941E-4EF6-803D-99580CE12B4B/Documents/temp/IMG_20170103_165104.jpg"
- "/var/mobile/Containers/Data/Application/FB3E4E5A-941E-4EF6-803D-99580CE12B4B/Documents/claims/claim1_2.jpg"

**Comment by daniel-luberda** [comment] 2017-01-03 15:56
@kamekjay Thanks for the info!

@Jelle-elaut I think it may be some other issue, related to permissions / wrong file path, not FFImageLoading. You can easily debug it by checking logs, using custom logger: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/iOS/AppDelegate.cs#L19-L50

Could you paste those exceptions here?

**Comment by Jelle-elaut** [comment] 2017-01-03 15:58
@daniel-luberda But that wouldn't explain why it works with a regular Xamarin Forms Image and not with the cached-image... That's why I think the problem is within the library, right?

**Comment by daniel-luberda** [comment] 2017-01-03 15:59
@Jelle-elaut It may be, but I can't do anything without more information as I don't know what the cause is.

**Comment by Jelle-elaut** [comment] 2017-01-04 07:44
@daniel-luberda  I tried adding the custom logger you linked, but the only feedback I get is the following line: 
`2017-01-04 08:42:32.478 AppiOS[9041:2093430] SimpleDiskCache path: /var/mobile/Containers/Data/Application/D9D2049D-B6DE-4C46-A245-8770D525B2C8/Library/Caches/FFSimpleDiskCache
`

**Comment by Jelle-elaut** [comment] 2017-01-04 08:21
@daniel-luberda I added the custom logger you linked, but this is the only feedback I get: 
`[0:] SimpleDiskCache path: /var/mobile/Containers/Data/Application/93FCC9CA-BE88-43CC-B29E-399F42567F1F/Library/Caches/FFSimpleDiskCache
`

**Comment by Ralle1986** [comment] 2017-01-05 12:24
@Jelle-elaut and @daniel-luberda. I also experience the same problem on IOS. There is no problem when i load an image, that is placed in the root of the Resource folder

like 
` var linearBackground = new CachedImage
            {
                WidthRequest = DeviceAgnostic.GetWidth(80),
                IsOpaque = true,
                CacheType = CacheType.Memory,
                Source = Device.OnPlatform("RatingBarDashboard", "RatingBarDashboard",null),
            };`

but it is not working, when i try to load an image from a folder inside the Resource folder

 like 
` var linearBackground = new CachedImage
            {
                WidthRequest = DeviceAgnostic.GetWidth(80),
                IsOpaque = true,
                CacheType = CacheType.Memory,
                Source = Device.OnPlatform("Rating/RatingBarDashboard", "RatingBarDashboard",null),
            };`

for me to get this to work, i have to add the file extention

like 
` var linearBackground = new CachedImage
            {
                WidthRequest = DeviceAgnostic.GetWidth(80),
                IsOpaque = true,
                CacheType = CacheType.Memory,
                Source = Device.OnPlatform("Rating/RatingBarDashboard.png", "RatingBarDashboard",null),
            };`

all my picture is divided in 3 formats RatingBarDashboard.png, RatingBarDashboard@3x.png, RatingBarDashboard@3x.png, but i can see if, last option, where i provide the file extention, take the right format.

Rasmus

**Comment by daniel-luberda** [comment] 2017-01-05 13:18
Here's the bundle resolver code: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/DataResolvers/BundleDataResolver.cs#L18

I'll try to debug it soon. Meanwhile, if you see anything that could be improved, please let me know.

**Comment by DavyHubrecht** [comment] 2017-02-09 16:37
I'm having the exact same issue, any progress on this?

**Comment by DavyHubrecht** [comment] 2017-02-10 08:37
More information: I try to load "faq_family.png" which is in an imageset on iOS. I first tried it just with the string "faq_family", which works on Android, but not on iOS. Added .png at the end also didn't work.

In a normal "Image" component this works without a problem.

Stacktrace:
> 2017-02-10 09:33:27.587 AppiOS[5090:2574477] Image loading failed: faq_family.png
System.IO.FileNotFoundException: faq_family.png
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x004ea] in <a0b5ebc3ea9b42969ed8ac6666032867>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3988/e02d2723/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3988/e02d2723/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerSe
rvices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3988/e02d2723/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3988/e02d2723/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3988/e02d2723/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at FFImageLoading
.Work.ImageLoaderTask`2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x00278] in <f4620c0a205341c78392982edfca72a6>:0

**Comment by daniel-luberda** [comment] 2017-02-10 16:57
Here's the resolver code: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/DataResolvers/BundleDataResolver.cs#L18

Any ideas how could I fix that?

**Comment by Ralle1986** [comment] 2017-02-13 21:56
line 77, change it to this

` string path = !string.IsNullOrEmpty(filenamePath) ? bundle.PathForResource(file, null, filenamePath) : bundle.PathForResource(file, null);
                 `

the filenamePath was never used, so it won´t look in subfolders, the bundle.PathForResource will just return null.

Hope it helps

**Comment by daniel-luberda** [comment] 2017-02-24 17:27
@Ralle1986 Nice catch!! :) Thanks! I'll release new nuget soon.

**Closed by daniel-luberda** 2017-02-24 17:27 UTC
Labels: help wanted
