### ISSUE TITLE
How to change color Svg image file ?

### ISSUE THREAD

**Issue by phamthanhtong** [luberda-molinet/FFImageLoading#609] opened 2017-05-22 03:30 UTC
Hi,
About svg image color, It is display is incorrectly.
iPhone and some Android devices is display color correctly.
![svgtouch](https://cloud.githubusercontent.com/assets/20292327/26297893/29ba22f0-3eff-11e7-868f-14db26068c4c.png)

But Nexus S (Android 6.0) is displaying image color incorrectly.
![svgdroid6 0](https://cloud.githubusercontent.com/assets/20292327/26297838/f218a75e-3efe-11e7-91b6-b46c31feb7a6.png)
I have above problem, how to fix it?
And could it change color Svg image file the same as TextColor in Label view?
Thanks!

**Comment by Nuada26** [comment] 2017-05-22 09:22
I think u have to give your code for help. With code he can try to repeat error and found why this bug come .

**Comment by michelmoorlag** [comment] 2017-05-22 09:34
I think it is the same problem as #605
See: https://github.com/luberda-molinet/FFImageLoading/issues/605

**Comment by phamthanhtong** [comment] 2017-05-22 09:42
Hi,
More explain my problem. Please view my code.
SVG images I download from Internet and I added into Resources folder of plaforms project:
Link images:
* wiki.svg  -> http://s.cdpn.io/3/kiwi.svg
*svg_logo.svg  -> https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg
```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:DemoSVG"
    xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
    x:Class="DemoSVG.DemoSVGPage">
    <ScrollView Orientation="Vertical">
        <StackLayout Orientation="Vertical">
            <Label Text="Welcome to Xamarin Forms!"
                VerticalOptions="Center"
                HorizontalOptions="Center" />
            <ffimageloadingsvg:SvgCachedImage WidthRequest="200"
                HeightRequest="100"
                Source="logo.svg" />
            <ffimageloadingsvg:SvgCachedImage WidthRequest="200"
                HeightRequest="100"
                BackgroundColor="Red"
                Source="SVG_logo.svg" />
            <ffimageloadingsvg:SvgCachedImage WidthRequest="200"
                HeightRequest="100"
                BackgroundColor="Green"
                Source="arrow.svg" />
            <ffimageloadingsvg:SvgCachedImage WidthRequest="200"
                HeightRequest="200"
                BackgroundColor="Green"
                Source="kiwi.svg" />
        </StackLayout>
    </ScrollView>
</ContentPage>
```

**Comment by ericruelas** [comment] 2017-05-23 21:41
can i also ask how to reference the svg file in a pcl project to only put them in one folder?

**Comment by michelmoorlag** [comment] 2017-05-24 06:48
Hi ericruelas,
I have the same question as you. I found a solution but that only works for Android I found out later. See my posting from may 15 in this thread: https://forums.xamarin.com/discussion/83234/ffimageloading-svg .
The solution that I now use is the Xamared.forms.svg plugin. Simply add it to all your projects and add the namespace to your xaml. Add the svg to your pcl set it as embedded resource. No add a svgview and reference the svg resourceid. Simple and effective.

**Comment by MaitlandMarshallMEX** [comment] 2017-06-01 02:07
I have the same problem. The Brainflab solution didn't work for me either. Any ideas?

**Comment by daniel-luberda** [comment] 2017-06-05 23:27
- It's a duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/605 - please continue there. 
- It's a SkiaSharp issue, downgrade SkiaSharp package, or wait for the upcoming 1.58.1
- It's probably emulator only issue too

**Closed by daniel-luberda** 2017-06-05 23:27 UTC
