### ISSUE TITLE
[Duplicate due to HTTP 500] Sometimes wrong image / same image as other CachedImage on the same site

### ISSUE THREAD

**Issue by Sebastian1989101** [luberda-molinet/FFImageLoading#1003] opened 2018-04-03 21:20 UTC
### Description

Sometimes the when used multiple images with this library they get messy and the long image is on the wrong control in the end. I got many reports with this problem lately since I use a lot images within my app. All images exists and in 80% of all cases they stay where they belong to. 

### Steps to Reproduce

I got the issue myself on iOS now a few times. For Android I only got user reports but I was not able to reproduce it myself. I guess this bug occurs when the RAM is nearly full because it happens a lot on older devices and much less on newer models. 

### Expected Behavior

Either the CachedImage should load the correct image or at least stay empty until it can show the correct image. 

### Actual Behavior

Sometimes displays the same image as another CachedImage on the site. 

### Basic Information

- Version with issue: 2.3.6
- Last known good version: none
- Platform: Xamarin.Forms (iOS + Droid)

### Screenshots

No screenshot available yet

### Reproduction Link / Code

No example repo created yet

**Comment by daniel-luberda** [comment] 2018-04-04 13:58
Could share your code to show how you're loading those images?

**Comment by daniel-luberda** [comment] 2018-04-04 14:00
Duplicate of #1004

**Closed by daniel-luberda** 2018-04-04 14:00 UTC
Labels: more info needed
