### ISSUE TITLE
SVG Image shows with black fill

### ISSUE THREAD

**Issue by abenedykt** [luberda-molinet/FFImageLoading#1109] opened 2018-09-06 11:19 UTC
SVG File shows with black fill in a newest version. After upgrading to the newest nuget images shows with black 

- Platform: Nexus 4 Android 5.1.1
- Nuget 2.4.3.840
- Xamarin.Forms 3.1.0.697729

Facebook button shows correctly, wheres the second one not so much. It did worked in the version 2.3.6 from which I was upgrading.

```
<ffimageloadingsvg:SvgCachedImage  Source="login_with_facebook.svg">
                            <ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                                <TapGestureRecognizer Tapped="Login_Clicked"/>
                            </ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                        </ffimageloadingsvg:SvgCachedImage>
```
### Screenshots
with ver  2.4.3.840 (incorrect)
![image](https://user-images.githubusercontent.com/2996107/45154274-4647dd80-b1d7-11e8-8326-8c80970c936e.png)

with ver 2.3.6 (correct)
![image](https://user-images.githubusercontent.com/2996107/45154888-5e206100-b1d9-11e8-8fbd-eaabd9e89319.png)

[svg-examples.zip](https://github.com/luberda-molinet/FFImageLoading/files/2356743/svg-examples.zip)

**Comment by AxelUser** [comment] 2018-09-24 18:28
Hi there!
This problem may be caused by this bug mono/SkiaSharp.Extended#42

**Comment by mattleibow** [comment] 2018-10-04 12:38
Sorry for the long delay with getting things merged. I was travelling, working on Xamarin.Essentials and then dealing with a few larger bugs in the next SkiaSharp release. Things seem to be calming down, so I hope to get a nice new release out soon.

**Comment by daniel-luberda** [comment] 2019-04-06 17:40
Fixed

![Uploading Simulator Screen Shot - iPad Pro (12.9-inch) (2nd generation) - 2019-04-06 at 19.39.44.png…]()

**Closed by daniel-luberda** 2019-04-06 17:40 UTC
Labels: SVG, investigating ...
