### ISSUE TITLE
Images in list getting mixed up

### ISSUE THREAD

**Issue by markmni** [luberda-molinet/FFImageLoading#354] opened 2016-11-01 14:18 UTC
Hi,

I'm seeing that when using FFImageLoading for images in lists, images are sometimes mixed up between the list items, I was wondering if you could provide some guidance?

I've created a small app to reproduce the issue in Xamarin.Android using ImageViewAsync, it has some numbered images which I am loading from a local webserver, the code can be found here:
https://github.com/markmni/FFImageTesting

When scrolling, the image that was previously in the reused cell appears until the new one loads in. I can work around this by setting the drawable to null when the view is retrieved in the adapter before loading the new image, but is this intended behaviour?

Images can still appear next to the wrong entry even after loading is complete, even with setting the image drawable to null before loading. It seems like with the recycled cells maybe whichever request completes last 'wins', rather than the one initiated most recently? Many Thanks

**Comment by daniel-luberda** [comment] 2016-11-02 19:49
> When scrolling, the image that was previously in the reused cell appears until the new one loads in. I can work around this by setting the drawable to null when the view is retrieved in the adapter before loading the new image, but is this intended behaviour?

Yes, it is. 

> Images can still appear next to the wrong entry even after loading is complete, even with setting the image drawable to null before loading. It seems like with the recycled cells maybe whichever request completes last 'wins', rather than the one initiated most recently? 

This should be fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/3997d79c1fbb53ce4544e3a49879a24bb3854b06

Could you test the newest prerelease?

**Comment by alanspires** [comment] 2016-11-02 19:53
Having a placeholder image seems to fix this too.

**Comment by markmni** [comment] 2016-11-03 23:11
Thanks both, I tried the latest prerelease and setting a placeholder image, but unfortunately images are still going astray. 

I tried a quick workaround in client code markmni/FFImageTesting@91c9d0790be0269f4cfac0488a4b81cc22238d07 by storing a reference to the scheduled work on the image, then explicitly cancelling it before loading the new image, which (GC implications aside) does seem to stop the problem, in case that's useful in tracking down the issue.

**Comment by daniel-luberda** [comment] 2016-11-04 00:50
The source of the problem is here: 
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs#L122-L154 (returns drawable size)
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs#L94-L97 (animation ends)

Somehow, drawable is not invalidated correctly after animation ends. Any ideas how could we fix this?

**Comment by daniel-luberda** [comment] 2016-11-04 04:56
It's fixed. Thanks for you help.

**Closed** 2016-11-04 04:55 UTC
Labels: help wanted
