### ISSUE TITLE
Make TintTransformation.HexColor a bindable property

### ISSUE THREAD

**Issue by odyodyodys** [luberda-molinet/FFImageLoading#931] opened 2018-02-05 16:20 UTC
### Description
It would be **really** helpful if the `TintTransformation.HexColor` property was bindable

### Basic Information

- Version with issue: Current
- Platform: All

**Comment by daniel-luberda** [comment] 2018-03-20 14:50
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/860 and https://github.com/luberda-molinet/FFImageLoading/issues/499

**Closed by daniel-luberda** 2018-03-20 14:50 UTC
