### ISSUE TITLE
FFImageLoading not working on Xamarin.forms using .Net Standard 2.0

### ISSUE THREAD

**Issue by kahaeia1** [luberda-molinet/FFImageLoading#947] opened 2018-02-18 14:16 UTC
### Description

FFImageLoading is not working with .Net Standard 2.0.

### Steps to Reproduce

1. Create a new Xamarin.Forms project with .Net Standard 2.0 called FF for Android, UWP.

2. Add the Nuget packages

3. Add the following line to the Android

CachedImageRenderer.Init(enableFastRenderer: true);

4. Add a new image to the PCL project called MyGif.gif

5. Change the MainPage to:

<?xml version="1.0" encoding="utf-8"?>

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:FF"
             xmlns:ff="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:viewModels="clr-namespace:FF.ViewModels;assembly=FF"
             x:Class="FF.MainPage">
    <ContentPage.Content>
        <StackLayout Orientation="Vertical">
            <ff:CachedImage Source="resource://FF.MyGif.gif"  />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

### Expected Behavior

Show the image in the view

### Actual Behavior

It doesn't show the image

### Basic Information

- Version with issue: 2.3.4
- Last known good version: ?
- Platform: Windows 10

**Comment by ozzy1873** [comment] 2018-02-19 03:00
It's working for me on UWP, Android and iOS.

**Comment by kahaeia1** [comment] 2018-02-19 07:57
Interesting. I debugged this for a couple of hours but I couldn't get it to work. 

Do you keep the images in the .Net Standard PCL or the platform specific projects? Could you provide more information about what version of FFImageLoading you used, etc? Would it be possible to share the code?

**Comment by daniel-luberda** [comment] 2018-02-26 13:55
@kahaeia1 If you keep your files in another assembly, you must specify it, as stated here: https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)#embedded-resources-uri-support

or use `new EmbeddedResourceImageSource(resourceName, assembly)`

Also possible duplicate of: https://github.com/luberda-molinet/FFImageLoading/issues/910

**Comment by kahaeia1** [comment] 2018-02-26 21:36
@daniel-luberda I did use resource://{resourceName} exactly how it was taught in https://www.youtube.com/watch?v=eVA9C7Ik_AM&t=313s and it didn't work.

**Comment by alustrement** [comment] 2018-03-07 10:31
Arf, maybe my problem came from here. The ImageCache does not work on my Xamarin forms project using dotnet standard 2.0. I've just had the ImageCache on my ContentPage with an http URL as Source, but it never shows anything, and without error.

**Comment by abrasat** [comment] 2018-03-07 13:13
Whre exactly in the samples can be found a Xamarin.Forms project (IoS, Droid, UWP), where FFImageLoading is used from a .NetStandard 2.x library ?
Thx for help.

**Comment by daniel-luberda** [comment] 2018-03-20 16:32
See this: https://github.com/luberda-molinet/FFImageLoading/issues/979

**Closed by daniel-luberda** 2018-03-20 16:32 UTC
Labels: more info needed
