### ISSUE TITLE
Performance degraded from 2.0.7 to 2.1.0-rc3

### ISSUE THREAD

**Issue by coonmoo** [luberda-molinet/FFImageLoading#206] opened 2016-05-17 15:21 UTC
Hello,

scrolling our ListView which is image intense became sluggish when we upgraded from 2.0.7 to 2.1.0-rc3.

Tested on Nexus5 Android 6.

Our ListView is basically a Twitter stream with large Picture + Profile Picture.

**Comment by molinch** [comment] 2016-05-17 18:21
Do you have some transformations?

**Comment by molinch** [comment] 2016-05-17 23:38
Would it be possible to check your app with branch changes https://github.com/luberda-molinet/FFImageLoading/tree/scheduler-changes ?

**Comment by coonmoo** [comment] 2016-05-18 15:01
Heya,

I don't use any transformation.
Xamarin.Foms 2.2.0 (latest stable).

I'll try to check the changes as soon as possible.
Thank you!

**Comment by daniel-luberda** [comment] 2016-05-18 18:06
@coonmoo Are you sure that performanxe differences don't come from XamarinForms 2.2 changes? (lot layout handling changes).

**Comment by molinch** [comment] 2016-05-18 20:38
@coonmoo There was definitely a massive regression on Android: memory cache was no longer used...
That's now fixed https://github.com/luberda-molinet/FFImageLoading/commit/ec3822e0d22a92e9a9f9be12b83f1204c9d08a60

**Comment by molinch** [comment] 2016-05-19 06:19
Could you tell us if things are back to normal?
Please note that 2.2 will be a performance release: we have tons of ideas to improve things.

**Comment by coonmoo** [comment] 2016-05-19 11:15
Performance of 2.1.0 is better than with  2.1.0-rc3.

But our list is still a little bit sluggish (2.0.7 was running totally smooth).

**Comment by bspinner** [comment] 2016-05-20 10:21
For us there is no real difference between 2.1.0 and 2.1.0-rc3.
One thing I'm wondering about: Is it ok, that `OnFreeResources` is being called very often in my app while scrolling in a listview?

**Comment by molinch** [comment] 2016-05-20 13:46
@bspinner Do you have a performance regression too?
Yes it is normal to have OnFreeResources called many times while scrolling.

**Comment by daniel-luberda** [comment] 2016-05-21 15:27
@bspinner @coonmoo Are you sure the performance difference isn't related to Xamarin.Forms itself? Did you try on XF < 2.2?

**Comment by mattfinch1980** [comment] 2016-05-23 10:53
Hi, I upgraded to XF 2.2.0.31 then needed to upgrade FFImageLoading to 2.1.0-rc3 for compatibility. I use CachedImage in listview and FFImageLoading previous official release with XF previous offical release was working great. Now with latest versions, image loading performance is similar between using either CachedImage or standard Image in 2.2.0.31..i.e not the excellent improvements experienced in scolling etc with last XF version! Now...I'm not sure what has been altered in new XF and where the problem lies...just some observations from the upgrades.

**Comment by daniel-luberda** [comment] 2016-05-25 15:56
@mattfinch1980 We noticed some threading issues in 2.1, fix is coming soon.

**Comment by molinch** [comment] 2016-05-26 14:35
@bspinner @mattfinch1980 @coonmoo @ravensorb We just upload alpha packages to nuget that contain massive performance improvements.

Could you give us your feedback on these?
Please don't consider these as production ready!

**Comment by michaeldimoudis** [comment] 2016-05-26 16:04
Hi haven't tested the new alpha packages extensively, but I got this crash in insights. When I went back to the page (image wasn't in a ListView) the image loaded successfully. This was on Android.

System.ObjectDisposedExceptionCannot access a disposed object. Object name: 'FFImageLoading.Drawables.SelfDisposingAsyncDrawable'.
Raw
Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
Android.Graphics.Drawables.Drawable.SetBounds(int left, int top, int right, int bottom)
FFImageLoading.Drawables.FFBitmapDrawable.OnBoundsChange(Rect bounds)
Android.Graphics.Drawables.Drawable.n_OnBoundsChange_Landroid_graphics_Rect_(IntPtr jnienv, IntPtr native__this, IntPtr native_bounds)
at (wrapper dynamic-method) System.Object:d5f46de0-a710-4870-9638-71944e069733 (intptr,intptr,intptr)

Also sometimes on iOS images in a ListView refused to load, I did a hard close, reopened the app and the images downloaded again.

Also 1 last thing, scrolling in a ListView in iOS still shows wrong images briefly during the scrolling. I'm using XAML DataTemplate ViewCell with image binding in the XAML Source="{Binding MyImage}". Do I need to use OnBindingContextChanged in the XAML code behind? When I tried that couldn't get the image loading at all :(, or I'm doing it wrong because I'm using XAML.

**Comment by daniel-luberda** [comment] 2016-05-26 16:20
@michaeldimoudis You should follow this: https://github.com/luberda-molinet/FFImageLoading/issues/200

I'll update wiki soon

**Comment by molinch** [comment] 2016-05-26 16:22
Just one thing: please don't mix different issues in the same issue.
Instead if you can create separate issues that's much easier to manage for us.
Thanks!

**Comment by molinch** [comment] 2016-05-26 16:31
@michaeldimoudis the `ObjectDisposedException` you reported was with 2.1.1 pre1 or 2.1.0 ?
Same question for iOS issue where images where no longer loaded.

**Comment by michaeldimoudis** [comment] 2016-05-26 16:39
It was all pre 1. Saw your Nuget update so thought I'd test it out. I believe with the iOS issue, it looks like it wants free network resources before even loading even a cached image?

**Comment by mattfinch1980** [comment] 2016-05-27 08:54
Hi,

 

Just upgraded to new 2.1.1 pre-release and tested with Xamarin Forms 2.2.0.31.

Compiled and run on Android so far. The use of cachedimage inside listview appears to have definitely improved since the last development release. Rapid scrolling on screen seems fine.

 

I will experiment further by increasing the count of cells within the listview and adding additional image loading processes.

 

Thanks for the effort and development.

 

Best Regards,

Matt

**Comment by molinch** [comment] 2016-05-30 19:20
Closing since performance are much better in prerelease.
If you encounter bugs please create new issues.

**Closed by molinch** 2016-05-30 19:20 UTC
