### ISSUE TITLE
Svg-s are rendered pixelated 

### ISSUE THREAD

**Issue by kyurkchyan** [luberda-molinet/FFImageLoading#522] opened 2017-03-06 08:05 UTC
Take a look at this screenshot

![image](https://cloud.githubusercontent.com/assets/3243139/23601318/487cc710-0264-11e7-9886-fb5d4a03050a.png)

As you can see the image quality is very low. This is I believe because device screen scaling factor is not taken into consideration in the `SvgDataResolver`.  In the line where bitmap is created
`using (var bitmap = new SKBitmap((int)sizeX, (int)sizeY))`
Before supplying sizeX and sizeY to SKBitmap they should be multiplied by the screen scaling factor. And this would make the images look nice and crisp.

This might also be related to `UseDipUnits` property. I couldn't find any place that this property was taken in account during the image rendering. It's used to create cache keys but nothing else. I think there should be a code like this before creating SKBitmap

`if(UseDipUnits)
		    {
		        sizeX *= scalingFactor;
                sizeY *= scalingFactor;
            }`

One of the solutions could be having static property called `ScalingFactor `inside the `SvgDataResolver`, and set it to corresponding values inside iOS and Android projects.

`SvgDataResolver.ScalingFactor = (uint)UIScreen.MainScreen.Scale;`

`SvgDataResolver.ScalingFactor = (uint)Resources.DisplayMetrics.Density;`

**Comment by xperseguers** [comment] 2017-03-07 14:25
I agree, confirming the bug.

**Comment by riandesign** [comment] 2017-03-19 16:44
Same issue.

**Comment by VincentH-Net** [comment] 2017-03-20 12:31
Confirmed; same bug. Blocking for production apps.
Can't use FFImageLoading for SVG until this is fixed.

Please fix this quickly, thx!
PS Anyone tried the fix suggested by @kyurkchyan ?

**Comment by VincentH-Net** [comment] 2017-03-20 15:18
I wrote a temporary fix, implementing @kyurkchyan 's suggestions.
For ppl who can't wait for the official fix, here is the code (only needed to change 3 lines):
[SharpSvgImageSource.cs](https://gist.github.com/VincentH-Net/1eb516aa1a12b00e6c0f50acb568adae)

It seems to be working just fine. Here are screenshots from an iPhone 7 and a Google Pixel XL:
![sharpsvg_iphone7](https://cloud.githubusercontent.com/assets/1872271/24106530/6c5bd64c-0d88-11e7-9593-21d1594d2a8a.PNG)
![sharpsvg_pixelxl](https://cloud.githubusercontent.com/assets/1872271/24106529/6c5b82e6-0d88-11e7-9d04-750a66ca330c.png)

**Comment by daniel-luberda** [comment] 2017-04-04 11:19
Fixed with this: https://github.com/luberda-molinet/FFImageLoading/commit/582fa2199e056b9aebe42876bd252dc160c24f9b

Somehow i missed to implement that property. @kyurkchyan @VincentH-Net Thanks for help! :) Nuget today.

**Comment by winterdouglas** [comment] 2017-06-15 15:50
@daniel-luberda is this included in any pre-release version? I'm facing the same problem here using the pre release 362 and I couldn't find which pre-release has this fix applied. Thank you.

**Comment by CarLoOSX** [comment] 2017-09-27 12:47
I'm having this bug after updating the ffimageloading to the last version , but only in Android. 
![captura de pantalla 2017-09-27 a las 14 47 15](https://user-images.githubusercontent.com/9008334/30914133-cfc482a6-a392-11e7-9d1b-2c1d9179c799.png)

**Comment by daniel-luberda** [comment] 2017-09-27 16:10
#CarLoOSX As always, did you try to clean, delete all `bin` / `obj` folders, then rebuild?

**Comment by daniel-luberda** [comment] 2017-09-27 16:13
@CarLoOSX There should be some logs about it in console. Please read this: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#downsampletoviewsize-bool-default-false

**Comment by MosCD** [comment] 2018-03-28 06:38
I am having the same problem even after updating to the latest v2.3.5 
Please tell me what should I do cuz this is messing up all app icons

Regards

**Comment by charlesroddie** [comment] 2018-03-28 23:22
I believe there is a current problem where some scaling is done related to aspect ratios and integer rounding. (This is independent of the OP's analysis and the fix in this thread where rendering used to be done as if device independent units corresponded to pixels.)

My observations here:
https://github.com/luberda-molinet/FFImageLoading/issues/958#issuecomment-375110196

**Comment by daniel-luberda** [comment] 2018-03-29 12:17
@MosCD Are you using DownsampleToViewSize?

@charlesroddie Let's continue there: https://github.com/luberda-molinet/FFImageLoading/issues/958#issuecomment-375110196

**Closed by daniel-luberda** 2018-03-29 12:17 UTC

**Comment by MosCD** [comment] 2018-04-02 11:14
No am not using that option
I also updated to the latest Nuget
Still problem exists
<img width="390" alt="screen shot 2018-04-02 at 2 13 51 pm" src="https://user-images.githubusercontent.com/32604165/38194434-2c78c298-3680-11e8-9d88-e0d26c48a504.png">
