### ISSUE TITLE
[Android] Broken Image with AspectFill

### ISSUE THREAD

**Issue by rredoh** [luberda-molinet/FFImageLoading#1148] opened 2018-11-09 03:02 UTC
### Description

Can you check this [issue](https://github.com/xamarin/Xamarin.Forms/issues/4133) ?
Because now it's working with Xamarin.Forms Image but it's still not working with CachedImage. Thanks :)

**Comment by hartez** [comment] 2018-11-15 16:23
@rredoh Where are you finding the type `CachedImage`? I don't think that's a Forms type.

**Comment by nbsoftware** [comment] 2018-11-21 17:43
Hello, I'm having this issue too with latest stable FFImageLoading (2.4.4.859) and Xamarin Forms 3.4.0.1008975.

See screenshots:

Android:
![android](https://user-images.githubusercontent.com/1502008/48858998-33e44580-edbd-11e8-89b5-0f11d5f91472.png)

iOS:
<img width="101" alt="ios" src="https://user-images.githubusercontent.com/1502008/48858952-13b48680-edbd-11e8-92bb-5958afa2e933.png">

**Comment by nbsoftware** [comment] 2018-11-22 13:37
Hmmm... I can't because I need the `DownsampleToViewSize` functionality from FFImageLoading to release pressure on memory (I don't have thumbnails available).

I'd be better off downgrading Xamarin Forms & FFImageLoading altogether because, but that's a pain too...

Daniel, any idea?

**Comment by rredoh** [comment] 2018-11-23 02:46
Sure, you can downgrade. In my case I can't downgrade because I need TitleView with Command Binding

**Comment by pkolosov** [comment] 2018-11-26 16:05
Broken Aspect Fill + **No Background Color.**

Simplest project VS 15.9.2

    <StackLayout>
        <ffimageloading:CachedImage 
            Margin="10"    HeightRequest="100"   WidthRequest="100"
            Aspect="AspectFit" 
	    HorizontalOptions="Center" VerticalOptions="Center"
            BackgroundColor="Gray"/>        

        <ffimageloading:CachedImage 
            Margin="10"   HeightRequest="50"   WidthRequest="100"
            Aspect="AspectFill" 
	    Source="xam_icon.png" HorizontalOptions="Center" VerticalOptions="Center"
            BackgroundColor="Gray"/> 

        <ffimageloading:CachedImage 
            Margin="10"   HeightRequest="100"   WidthRequest="100"
            Aspect="Fill"  HorizontalOptions="Center" VerticalOptions="Center"
            BackgroundColor="Gray"/>
    </StackLayout>

Xamarin Forms 3.1 + FFImage 2.4.2  = OK

![test1](https://user-images.githubusercontent.com/44863121/49025239-43dc9a80-f1ac-11e8-93a6-54727994baec.png)

Xamarin Forms 3.4 + FFImage 2.4.4.859 & 860_pre  = 

![test2](https://user-images.githubusercontent.com/44863121/49025241-43dc9a80-f1ac-11e8-941a-46531fdb1c7c.png)

Between this versions - inialization errors only .

**Comment by nbsoftware** [comment] 2018-12-05 06:59
Hi Daniel,

Could you have a look at this one?

This issue is blocking me from releasing my app :/

At least unless I painfully downgrade every component...

Would be very appreciated.

Thanks

**Comment by rredoh** [comment] 2018-12-08 08:31
Hi @daniel-luberda ,
Could you check this?

**Comment by jeremymarabel** [comment] 2018-12-12 13:59
Hi, I have the same issue (last version of XF and FFImageLoading). Did someone find any workaround other than downgrading or using xamarin image control ?

**Comment by nbsoftware** [comment] 2018-12-12 15:37
Unfortunately no.
As this is only happening with Android, I'm still waiting for @daniel-luberda to take a look at this one...

**Comment by velocitysystems** [comment] 2018-12-14 15:22
@daniel-luberda @nbsoftware I have a PR up for this now which brings over the fix from XF.

**Comment by rredoh** [comment] 2018-12-15 03:12
Thanks for your effort @velocitysystems :)
Please do an update @daniel-luberda

**Comment by rredoh** [comment] 2018-12-17 04:18
For those who can't waiting for the official update, base on @velocitysystems solution, you can add this renderer

```
using Android.Content;
using Android.Graphics;
using Assetku.Droid.Renderers;
using FFImageLoading.Forms;
using FFImageLoading.Forms.Platform;
using Xamarin.Forms;

[assembly: ExportRenderer(typeof(CachedImage), typeof(FFImage_CachedImageRenderer))]
namespace Assetku.Droid.Renderers
{
    class FFImage_CachedImageRenderer : CachedImageFastRenderer
    {
        public FFImage_CachedImageRenderer(Context context) : base(context)
        {
        }

        protected override void OnLayout(bool changed, int left, int top, int right, int bottom)
        {
            base.OnLayout(changed, left, top, right, bottom);
            ClipBounds = GetScaleType() == ScaleType.CenterCrop ? new Rect(0, 0, right - left, bottom - top) : null;
        }
    }
}
```

**Comment by velocitysystems** [comment] 2018-12-17 11:54
@rredoh To use your workaround, you'll also need to:

1. Add this to your renderer:
```
public static void OverrideDefaultFastRenderer()
{
    var assembly = typeof(Xamarin.Forms.Image).Assembly;
    Type registrarType = assembly.GetType("Xamarin.Forms.Internals.Registrar") ?? assembly.GetType("Xamarin.Forms.Registrar");
    var registrarProperty = registrarType.GetProperty("Registered", BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);

    var registrar = registrarProperty.GetValue(registrarType, null);
    var registerMethod = registrar.GetType().GetRuntimeMethod("Register", new[] { typeof(Type), typeof(Type) });
    registerMethod.Invoke(registrar, new[] { typeof(CachedImage), typeof(FFImage_CachedImageRenderer) });
}
```

2. Call OverrideDefaultFastRenderer after calling `CachedImageRenderer.Init`:

```
FFImageLoading.Forms.Platform.CachedImageRenderer.Init(enableFastRenderer);
FFImage_CachedImageRenderer.OverrideDefaultFastRenderer();
```

**Comment by rredoh** [comment] 2018-12-17 15:12
Thanks @velocitysystems  :)

**Comment by nbsoftware** [comment] 2018-12-19 16:08
I can confirm it works as expected with this workaround.
Thanks!!

**Comment by daniel-luberda** [comment] 2019-02-13 11:52
Fixed with https://github.com/luberda-molinet/FFImageLoading/pull/1170
Thanks @velocitysystems

**Closed by daniel-luberda** 2019-02-13 11:52 UTC

**Comment by titonton** [comment] 2019-03-07 19:31
Is this in preview? The image is still bleeding out of it's view with DownSampleToViewSize prop enabled. I have version 2.4.4.859
