### ISSUE TITLE
UWP release mode

### ISSUE THREAD

**Issue by bprochniak** [luberda-molinet/FFImageLoading#759] opened 2017-10-13 10:00 UTC
No image is dispaly in UWP in Release mode:
            
```
<ffimageloading:CachedImage x:Name="previewImage" DownsampleToViewSize="true" LoadingPlaceholder="loading.svg" ErrorPlaceholder="loading.svg" 
                                        HorizontalOptions="CenterAndExpand" Source="{ Binding GalleryManager.Preview.ProfileImageUrl }" 
                                        Transformations="{ Binding GalleryManager.Preview.Rotation, Converter={x:Static local:RotateToTransformationConverter.Instance}}"
                                        Aspect="AspectFit" Grid.Row="0" />     
```

when I remove this line:

`Transformations="{ Binding GalleryManager.Preview.Rotation, Converter={x:Static local:RotateToTransformationConverter.Instance}}"`

it is working fine. It is working fine also in Debug mode with this line. I my App.xaml.cs I have:

```
var assembliesToInclude = new List<Assembly>()
                {
                    typeof(CachedImage).GetTypeInfo().Assembly,
                    typeof(CachedImageRenderer).GetTypeInfo().Assembly,
                    typeof(FFImageLoading.Transformations.RotateTransformation).GetTypeInfo().Assembly
                };

                Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```

What else I need to do to make it work? 
Version 2.2.20

**Comment by daniel-luberda** [comment] 2017-10-16 14:28
@bprochniak Many people have problems with this. Is it possible to have a reproduction project? I currently don't know why is it happening. Does anyone knows what's the cause?

**Comment by daniel-luberda** [comment] 2017-10-16 15:02
This may be related: https://github.com/luberda-molinet/FFImageLoading/issues/762

**Comment by Aquastorm** [comment] 2017-10-16 22:15
@daniel-luberda Hello Daniel, I think this issue is related to [#508](https://github.com/luberda-molinet/FFImageLoading/issues/508) and that the cause is a regression in the [ImageExtension.cs](https://github.com/luberda-molinet/FFImageLoading/commits/master/source/FFImageLoading.Windows/Extensions/ImageExtensions.cs) file. 
The commit [80764a1](https://github.com/luberda-molinet/FFImageLoading/commit/80764a1108efab92fa6e5b1beb2f7a5c42ef2bc8#diff-f25439a213dbe065a36bdb12295d1998) (28 August 2017, title "Some refactorings") re-introduced the problem that was fixed by [#508](https://github.com/luberda-molinet/FFImageLoading/issues/508).

**Comment by bprochniak** [comment] 2017-10-17 07:00
I have not gone deep into this but I guess this issue occurs because a platform specific transformation dll is not included. The point is, how can I do it? 

Wit **FFImageLoading.Forms** it is easy. We have the pcl dll **FFImageLoading.Forms.dll** and the uwp dll **FFImageLoading.Forms.WinUWP.dll**. The first one I include by **typeof(CachedImage).GetTypeInfo().Assembly** and secend one by **typeof(CachedImageRenderer).GetTypeInfo().Assembly**. But there is no **FFImageLoading.Transformations.WinUWP.dll** file. There is only **FFImageLoading.Transformations.dll** file and the platform specific dll has the same name and the same namespace in it. So by **typeof(FFImageLoading.Transformations.RotateTransformation).GetTypeInfo().Assembly** I include only the pcl library and I guess I need to do something like this: 

**typeof(RotateTransformationRenderer).GetTypeInfo().Assembly** or **typeof(FFImageLoading.Transformations.WinUWP.RotateTransformation).GetTypeInfo().Assembly**

but I can't find this type / namespace.

**Comment by daniel-luberda** [comment] 2017-10-18 23:05
>The commit 80764a1 (28 August 2017, title "Some refactorings") re-introduced the problem that was fixed by #508.

@Aquastorm Nice catch! I applied a better fix now (IMainThreadDispatcher was faulty when using async methods with it) as it was the main issue. 

About Transformations. I think the problem is with Transformation package nuspec file, but I don't know what exactly.

**Comment by bprochniak** [comment] 2017-10-19 06:42
It is working fine with 2.2.21-pre576. Thanks.

**Closed** 2017-10-19 10:31 UTC
Labels: help wanted, Windows

**Comment by DVDPT** [comment] 2017-10-19 10:57
Also confirm that everything works fine, just in time for the release XD

**Comment by Aquastorm** [comment] 2017-10-20 08:07
@daniel-luberda Thanks Daniel :)
I can also confirm that everything works like a charm with the 2.2.2.1-pre-576 release. We are so happy that we can make a new release for Windows.
Thank you Daniel for the fix!
