### ISSUE TITLE
SVG is not rendered on UWP only.

### ISSUE THREAD

**Issue by ysmoradi** [luberda-molinet/FFImageLoading#1052] opened 2018-06-07 10:56 UTC
### Description

I've pushed a [simple/sample app on GitHub](https://github.com/ysmoradi/XamarinFormsPrismSvgSample)
It has an SVG file which gets rendered correctly on ios/android, but it doesn't work on UWP.

### Steps to Reproduce

Just run my sample app.

### Expected Behavior

App should work just fine on UWP as like as Android/iOS

### Actual Behavior

Svg is not working on UWP only.

### Basic Information

- Version with issue: Xamarin.FFImageLoading.Svg.Forms 2.4.1.823
- Platform: XF/UWP

### Reproduction Link / Code

https://github.com/ysmoradi/XamarinFormsPrismSvgSample

**Comment by daniel-luberda** [comment] 2018-06-07 13:48
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/1048

**Closed by daniel-luberda** 2018-06-07 13:48 UTC
