### ISSUE TITLE
FFImageLoading crashing every once in a while

### ISSUE THREAD

**Issue by AntonisSt** [luberda-molinet/FFImageLoading#644] opened 2017-06-20 08:24 UTC
Hi, every once in a while I get a sigsev exception. Got any idea what it might be? This is part of my stacktrace, since the rest just shows references and their rw rights:

> Stacktrace:
06-20 11:17:32.248 E/mono-rt (11316): 
06-20 11:17:32.248 E/mono-rt (11316):   at <unknown> <0xffffffff>
06-20 11:17:32.248 E/mono-rt (11316):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x0005b>
06-20 11:17:32.248 E/mono-rt (11316):   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x0008f] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12079
06-20 11:17:32.248 E/mono-rt (11316):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x00068] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:31
06-20 11:17:32.248 E/mono-rt (11316):   at Android.Widget.ImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x0002c] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Widget.ImageView.cs:1056
06-20 11:17:32.248 E/mono-rt (11316):   at FFImageLoading.Views.ManagedImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00013] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Views\ManagedImageView.cs:74
06-20 11:17:32.248 E/mono-rt (11316):   at FFImageLoading.Targets.ImageViewTarget.Set (FFImageLoading.Work.IImageLoaderTask,FFImageLoading.Drawables.SelfDisposingBitmapDrawable,bool) [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Targets\ImageViewTarget.cs:55
06-20 11:17:32.248 E/mono-rt (11316):   at FFImageLoading.PlatformImageLoaderTask`1/<>c__DisplayClass4_0<TImageView_REF>.<SetTargetAsync>b__0 () [0x0000b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:74
06-20 11:17:32.248 E/mono-rt (11316):   at FFImageLoading.Helpers.MainThreadDispatcher/<>c__DisplayClass5_0.<PostAsync>b__0 () [0x00008] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Helpers\MainThreadDispatcher.cs:44
06-20 11:17:32.258 E/mono-rt (11316):   at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36
06-20 11:17:32.258 E/mono-rt (11316):   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Java.Lang.IRunnable.cs:81
06-20 11:17:32.258 E/mono-rt (11316):   at (wrapper dynamic-method) object.892fb47d-cc44-45bf-89e7-bd839b657b43 (intptr,intptr) [0x00011] in <8c304e4006094a46a7950338a3b3cb5d>:0
06-20 11:17:32.258 E/mono-rt (11316):   at (wrapper native-to-managed) object.892fb47d-cc44-45bf-89e7-bd839b657b43 (intptr,intptr) [0x00021] in <8c304e4006094a46a7950338a3b3cb5d>:0 <

>No native Android stacktrace (see debuggerd output).
06-20 11:17:32.288 E/mono-rt (11316): 
06-20 11:17:32.288 E/mono-rt (11316): 
06-20 11:17:32.288 E/mono-rt (11316): =================================================================
06-20 11:17:32.288 E/mono-rt (11316): Got a SIGSEGV while executing native code. This usually indicates
06-20 11:17:32.288 E/mono-rt (11316): a fatal error in the mono runtime or one of the native libraries 
06-20 11:17:32.288 E/mono-rt (11316): used by your application.
06-20 11:17:32.288 E/mono-rt (11316): =================================================================
06-20 11:17:32.288 E/mono-rt (11316): 
06-20 11:17:32.288 F/libc    (11316): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x942dd240 in tid 11316 (ccount_official) <

**Comment by lukejaylarsen** [comment] 2017-06-22 01:21
Me too... 

> [mono-rt] Stacktrace:
[mono-rt] 
[mono-rt]   at <unknown> <0xffffffff>
[mono-rt]   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00057>
[mono-rt]   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00074] in <bd30a18775d94dc8b6263aecd1ca9077>:0
[mono-rt]   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005f] in <bd30a18775d94dc8b6263aecd1ca9077>:0
[mono-rt]   at Android.Widget.ImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00038] in <d855bac285f44dda8a0d8510b679b1e2>:0
[mono-rt]   at FFImageLoading.Views.ManagedImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable) [0x00013] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Views\ManagedImageView.cs:74
[mono-rt]   at FFImageLoading.Targets.ImageViewTarget.Set (FFImageLoading.Work.IImageLoaderTask,FFImageLoading.Drawables.SelfDisposingBitmapDrawable,bool) [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Targets\ImageViewTarget.cs:55
[mono-rt]   at FFImageLoading.PlatformImageLoaderTask`1/<>c__DisplayClass4_0<TImageView_REF>.<SetTargetAsync>b__0 () [0x0000b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:74
[mono-rt]   at FFImageLoading.Helpers.MainThreadDispatcher/<>c__DisplayClass5_0.<PostAsync>b__0 () [0x00008] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Helpers\MainThreadDispatcher.cs:44
[mono-rt]   at Java.Lang.Thread/RunnableImplementor.Run () [0x0000e] in <d855bac285f44dda8a0d8510b679b1e2>:0
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0
[mono-rt]   at (wrapper dynamic-method) object.722e7113-4414-493f-83aa-3d15ccdf753f (intptr,intptr) [0x00011] in <3fd174ff54b146228c505f23cf75ce71>:0
[mono-rt]   at (wrapper native-to-managed) object.722e7113-4414-493f-83aa-3d15ccdf753f (intptr,intptr) [0x00021] in <3fd174ff54b146228c505f23cf75ce71>:0

**Comment by AntonisSt** [comment] 2017-06-22 06:15
@lukejaylarsen have you found anything to this problem, even as a workaround?

**Comment by lukejaylarsen** [comment] 2017-06-22 06:26
Too early to say for sure, but simply using the built-in error method (something I was not doing before) seems to have stopped it crashing the app for me. 
E.g:

```
ImageService.Instance
	.LoadUrl (url)
	.Error ((ex) => {
		Console.WriteLine (ex.Message);
	})
	.Into (imageView);
```

As for the cause of the exception, I have been using the following when destroying an Activity:

			ImageService.Instance.SetExitTasksEarly (true);
			ImageService.Instance.InvalidateMemoryCache ();

I suspect if it was halfway through loading an image into a view and this code it runs into the error (haven't tested to confirm, though).

**Comment by AntonisSt** [comment] 2017-06-22 06:30
Thank you. I will try  these and update you about what's going on. I hope they fix this bug, it has given me a lot of frustration.

**Comment by AntonisSt** [comment] 2017-06-23 11:50
@lukejaylarsen  things seem to have been stabilized since I added the Error method. So I can say that your workaround is sufficient. Thx. Surely though, they have to find the reason of this kind of exceptions.

**Comment by daniel-luberda** [comment] 2017-08-12 18:22
Could you test the newest prerelease? (2.2.10.428) It should be fixed now. Please reopen if it's still a valid issue. Thanks

**Closed by daniel-luberda** 2017-08-12 18:22 UTC
Labels: investigating ...
