### ISSUE TITLE
With Xamarin 3.6, FFImageLoading.Forms.Platform.CachedImageRenderer.Init(true) Fails on Android

### ISSUE THREAD

**Issue by JeffWeber** [luberda-molinet/FFImageLoading#1212] opened 2019-03-07 19:40 UTC
### Description

Updated to Xamarin 3.6. When I attempt to deploy/run on an Android device, the app crashes on this line:

With Xamarin 3.6, FFImageLoading.Forms.Platform.CachedImageRenderer.Init(true)

### Steps to Reproduce

Update to Xamaring 3.6 and run your app.

### Expected Behavior

App will run without crashing.

### Actual Behavior

App crashed on:
FFImageLoading.Forms.Platform.CachedImageRenderer.Init(true) 

With the following exception:
Unhandled Exception:

System.TypeLoadException: Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>) occurred

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: ?
- Platform: Android

**Comment by JeffWeber** [comment] 2019-03-07 19:41
FYI, I did try wiping my bin and obj folders, but still failed.

**Comment by ewoody** [comment] 2019-03-07 19:57
Same issue.
Xamarin.Forms 3.6
FFImageLoading Version : 2.4.4.859

Good version - 
Xamarin.Forms 3.4

**Comment by samhouts** [comment] 2019-03-08 00:07
See https://github.com/luberda-molinet/FFImageLoading/issues/1154#issuecomment-470589841

**Comment by scharada** [comment] 2019-03-12 10:52
any idea when this can fixed pls ? it seems a a blocking issue unless we use a deprecated version (with old dependencies ...) 
thanks you.

**Comment by daniel-luberda** [comment] 2019-03-12 16:13
Please check `2.4.5.870-pre`. Cheers.

**Comment by daniel-luberda** [comment] 2019-03-12 16:27
Duplicate of: https://github.com/luberda-molinet/FFImageLoading/issues/1154

**Closed by daniel-luberda** 2019-03-12 16:27 UTC
