### ISSUE TITLE
Retry on Xamarin.iOS

### ISSUE THREAD

**Issue by owlstack** [luberda-molinet/FFImageLoading#329] opened 2016-10-05 15:27 UTC
When setting the image to a retry of 3 with 250ms delay, the image finds the correct image then defaults back to the errorplaceholder image instead of the actual image. 

Is this a bug? This only happens on Xamarin.iOS version. On the Xamarin.Forms version, it works fine. 

This happens on latest stable release: v2.1.8

```
 ImageService.Instance.LoadUrl(Image, TimeSpan.FromDays(5))
                .Retry(3, 250)
                .ErrorPlaceholder("Images/ErrorPlaceholder.png")
                .Into(imageView);
```

**Comment by daniel-luberda** [comment] 2016-10-05 20:55
@owlstack  Did you resolve it?

**Comment by owlstack** [comment] 2016-10-05 21:03
No I did not. Are you seeing the issue as well?

**Comment by owlstack** [comment] 2016-10-05 23:28
@daniel-luberda I have one more question. How do I add properties to preloaded images for Xamarin.iOS? E.g. 

I want to do something like this: 

```
ImageService.Instance.LoadUrl(Image, TimeSpan.FromDays(5)).Success(() =>
                {
                      //Do something on success
                })
		.Preload()
                .Retry(3, 250)
                .ErrorPlaceholder("Images/ErrorPlaceholder.png")
                .Into(imgView);
```

But it wouldn't let me. In Xamarin.Forms, we have a CachedImage that I can set the properties to but for Xamarin.iOS or Android.... we don't have that option. I want to preload the images and I want to set a retry and error placeholder for them.

Thanks!

**Comment by daniel-luberda** [comment] 2016-10-06 00:13
I don't understand your question. Could you give more details? It should be used exactly like this:

```C#
ImageService.LoadUrl("http://www.funchap.com/wp-content/uploads/2014/05/help-dog-picture.jpg")
.LoadingPlaceholder("loading.png")
.ErrorPlaceholder("error.png")
.Retry(3, 200)
.Into(_imageView);
```

**Comment by owlstack** [comment] 2016-10-06 00:20
@daniel-luberda Sorry, I got it thanks!

**Comment by daniel-luberda** [comment] 2016-10-06 00:22
@owlstack No problem. We need to update docs someday (collaboration welcome). What about first bug? I cannot reproduce it. Should I close it?

**Comment by owlstack** [comment] 2016-10-06 17:25
@daniel-luberda I need to test further but I think the issue with the retry is..... These images are loaded on a listview. When I scroll down or up the listview, I very briefly see another offer image for a particular cell... that is, the wrong image is loaded briefly on top of the cell which should have a different image. Then after that it defaults to placeholder....

**Comment by daniel-luberda** [comment] 2016-10-06 17:28
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled

Do you use cell recycling? If yes, read the wiki page above.

**Comment by owlstack** [comment] 2016-10-06 17:35
@daniel-luberda This is for Xamarin.iOS. Can I still use the method above? 

Also one thing to note, what "fixes" it is adding a LoadingPlaceholder. Is that the right approach? But I can't add the retry because it would no longer work.

**Comment by daniel-luberda** [comment] 2016-10-06 17:38
I though you're referring to Forms. On iOS / Android, you should set image to `null` before each loading:

```C#
imageView.Image = null;
```

**Comment by daniel-luberda** [comment] 2016-10-06 17:39
...and also you should cancel your previous image loading task.

**Comment by owlstack** [comment] 2016-10-06 17:43
> ...and also you should cancel your previous image loading task.

What do you mean? I can set the image to null but what do you mean by cancel?

**Comment by daniel-luberda** [comment] 2016-10-06 17:45
```C#
var imageLoadingTask = ImageService.Instance.LoadUrl(Image, TimeSpan.FromDays(5))
                .Retry(3, 250)
                .ErrorPlaceholder("Images/ErrorPlaceholder.png")
                .Into(imageView);

imageLoadingTask.Cancel();
```

**Comment by owlstack** [comment] 2016-10-06 17:50
If I use the approach above I would also need to load that imageLoadingTask right?

**Comment by daniel-luberda** [comment] 2016-10-06 17:51
Could you elaborate?

**Comment by owlstack** [comment] 2016-10-06 17:59
Just using ImageService would set the images for the imageView but setting it above... won't I need to call or set that variable above to something? Since you introduced a var?

**Comment by daniel-luberda** [comment] 2016-10-06 18:43
You can keep a reference to current task as here: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs#L26

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs#L272

**Comment by owlstack** [comment] 2016-10-06 19:02
@daniel-luberda but what do I do with the current task? Currently if I leave it how you set it above... none of the images are loaded? Where am I supposed to use imageLoadingTask in my view? I'm confused

**Comment by daniel-luberda** [comment] 2016-10-06 20:35
It's not because of FFImageLoading, but it's because how cells in iOS/Android are reused in lists / repeater views. When cells are reused , you get an old view which was used somewhere before and it eg. has some image loaded or there's already a task for image loading for it. To avoid showing old image, you should:

- cancel any previous image loading if exists (it can still load previous image in situations where user scrolled very fast)
- set image to `null` before loading
- run new image loading to that view

`.Into` method always return a new loading task which can be for example cancelled, using `Cancel` method.

**Comment by rusty21** [comment] 2016-10-10 20:15
Is there a way FFImageLoading can detect if you are trying to load a new image into an image view that already has a pending task and cancel that pending task for you?

**Comment by daniel-luberda** [comment] 2016-10-10 23:03
It does this automatically. But  when cells are reused, loading a new image takes some time, so Cancelling image from previous cell manually, setting image to `null` and then loading correct image gives a better user experience (old images are not shown in new cells when recycled).

**Comment by rusty21** [comment] 2016-10-25 18:00
I'm seeing some strange behavior with cancelling.  I've got a listview for demo purposes where each list item is set like this

    View view = convertView;
	if (view == null)
	{
		view = LayoutInflater.Inflate(Resource.Layout.ListViewItem, null);
	}

	ImageService.Instance.LoadUrl(url).Into(view.FindViewById<ImageViewAsync>(Resource.Id.imgImage));
	view.FindViewById<TextView>(Resource.Id.lblUrl).Text = url;
	
	ImageService.Instance.Cancel(m =>
	{
		if (m.Path == url)
		{
			System.Diagnostics.Debug.WriteLine("Canceled " + m.Path);
			return true;
		}
		return false;
	});

	view.FindViewById<ImageViewAsync>(Resource.Id.imgImage).SetImageResource(Resource.Drawable.Icon);

	return view;

All images are still loaded into their image views and none have been canceled.

**Comment by daniel-luberda** [comment] 2016-10-27 00:27
The newest alpha should solve those issues. Please reopen if it didn't work for you. Thanks.

**Closed by daniel-luberda** 2016-10-27 00:27 UTC
Labels: more info needed
